### ISSUE TITLE
UI : Show Alert Rule Name in Delete Confirmation Popup

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#100]
# Description
Currently, when attempting to delete an alert rule, the confirmation popup only displays a generic message:
`Are you sure you want to delete this Alert?`
To provide more context, we want to include the name of the alert rule in the confirmation popup.

# Steps to Reproduce:
1. Navigate to the Alerting screen.
2. Add a new alert rule.
3. Initiate the delete action.
4. Observe the confirmation popup.

# Expected Behavior:
The confirmation popup should display the name of the alert rule along with the generic confirmation message, like:
`Are you sure you want to delete the "AlertRuleName" alert?`

# Screenshot:
<img width="1435" alt="image" src="https://github.com/siglens/siglens/assets/71771131/07b7543a-89e0-4415-b563-2f9fe2bd2754">

**Comment by Shubhamvjagtap** [comment]
I would like work on it.

**Comment by PratikshaPatil77** [comment]
If no one has been working on this issue recently, I would want to work on it.

**Comment by AndrewHess** [comment]
Sure, go ahead

**Comment by PratikshaPatil77** [comment]
@sonamgupta21 Please let me know if the result below is what is expected or if any adjustments are needed.
<img width="882" alt="alert-rule" src="https://github.com/siglens/siglens/assets/128806421/0c105093-25f5-4454-9e5a-33e847f86d09">

**Comment by sonamgupta21** [comment]
> @sonamgupta21 Please let me know if the result below is what is expected or if any adjustments are needed. <img alt="alert-rule" width="882" src="https://private-user-images.githubusercontent.com/128806421/291494470-0c105093-25f5-4454-9e5a-33e847f86d09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5Njc2NTcsIm5iZiI6MTcwMjk2NzM1NywicGF0aCI6Ii8xMjg4MDY0MjEvMjkxNDk0NDcwLTBjMTA1MDkzLTI1ZjUtNDQ1NC05ZTVhLTMzZTg0N2Y4NmQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQwNjI5MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDE5ZWMwNzc0NTA3ZWRlMzAzMzI2MDBiNjNhMThjMzY4Yjc4MzdmZjljZTM3MWUzODE4ODE3NjM2MDFhNzVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sMBoQV9CyGJ-MMQqbC6CQqvkelePC-yo4IOQOd-Ixkk">

Looks good. Just make the "alert rule name" bold.

**Comment by PratikshaPatil77** [comment]
how it appears right now, is it okay?
<img width="827" alt="alert-rule" src="https://github.com/siglens/siglens/assets/128806421/be3d9c91-5fad-4175-a4dd-a36bed62a95e">

**Comment by sonamgupta21** [comment]
> how it appears right now, is it okay? <img alt="alert-rule" width="827" src="https://private-user-images.githubusercontent.com/128806421/291499186-be3d9c91-5fad-4175-a4dd-a36bed62a95e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5NjkwMTksIm5iZiI6MTcwMjk2ODcxOSwicGF0aCI6Ii8xMjg4MDY0MjEvMjkxNDk5MTg2LWJlM2Q5YzkxLTVmYWQtNDE3NS1hNGRkLWEzNmJlZDYyYTk1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOVQwNjUxNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzQ2Y2ViMzJjYjFlZWFmM2MzMDI3MjllM2JjYjVmOWYwYjY1OGQwODM2NzI3ZmI2NDczOGNjODg4Njk1NGI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p5cDmYcXaZY7IvwR1VZXKblCD1tNxfgrkKirp64Uzqw">

Yup! Looks good.
