### ISSUE TITLE
[NEW] Add Unit Tests for Arithmetic(+ - * /)  operators in metricsresults_test.go

### ISSUE THREAD

**Issue by Jiale-Fang** [siglens/siglens#1005]
# Description
We do not have unit test for arithmetic operators like: (+ - * /). Please add that in `metricsresults_test.go`.

Sample test for operator: modulo `%`
https://github.com/siglens/siglens/blob/dab7fdb8833a2f27485f02a5dc4e4021df1db2f2/pkg/segment/results/mresults/tests/metricsresults_test.go#L410-L437

**Comment by ahegde3** [comment]
Can I work on this ?

**Comment by nkunal** [comment]
Yes go ahead

*Best Regards*
*-- Kunal Nawale ,**Founder/CEO, SigScalr*
