### ISSUE TITLE
[STORY] Add atan2 operator

### ISSUE THREAD

**Issue by Jiale-Fang** [siglens/siglens#1009]
# Description

Add Trigonometric binary operators as mention in:
https://prometheus.io/docs/prometheus/latest/querying/operators/#trigonometric-binary-operators

We have a similar implementation here: https://github.com/siglens/siglens/pull/970. You can use a similar approach to complete that.

# (Optional) Testing
Describe how this should be tested and/or which files unit tests should be added to.

For documentation changes or other similar scenarios, this section can be deleted.

# Acceptance Criteria
List the concrete items that should be completed for this task to be considered completed. Be as clear and thorough as you can.

**Comment by AndrewHess** [comment]
Fixed by https://github.com/siglens/siglens/pull/1140
