### ISSUE TITLE
UI : Show Contact Name in Delete Confirmation Popup 

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#101]
# Description:
When deleting a contact point, the current confirmation popup provides a generic message for contacts used in alerts and a standard confirmation for others. To enhance user understanding, we want to show the name of the contact point being deleted.

# Current Behavior:
- If a contact point is used in alerts:
`Contact point cannot be deleted because it is used in more alerts. Please update or delete these alerts first.`
- Otherwise:
`Are you sure you want to delete this contact point?`

# Steps to Reproduce:
1. Navigate to the Alerting screen and go to the Contact Point tab.
2. Add a new contact point.
3. Initiate the delete action.
4. Observe the confirmation popup.

# Expected Behavior:
The confirmation popup should display the name of the contact point being deleted, such as:
- If a contact point is used in alerts:
`The contact point named 'ContactPointName' is currently in use by multiple alerts.`
- Otherwise
`Are you sure you want to delete the 'ContactPointName' contact point?`

# Screenshot:
<img width="1426" alt="image" src="https://github.com/siglens/siglens/assets/71771131/67fe8a6d-ad4a-419c-a043-bca77566ae63">
<img width="1434" alt="image" src="https://github.com/siglens/siglens/assets/71771131/fcef26c9-0fa6-4faf-a45f-c64bd3964096">

**Comment by sai-vivekanand** [comment]
Can I work on this issue?
