### ISSUE TITLE
[STORY] Add Unit Tests / E2E Tests for various Wildcard Search Patterns. 

### ISSUE THREAD

**Issue by Macbeth98** [siglens/siglens#1037]
# Description
- In logs search, users can search using Wildcards.
- Example Searches
   - `app_name=ab*`
   - `http_status=3*1`
- Write some unit tests or e2e tests to test various patterns of Wildcards.

# Acceptance Criteria
- The tests should be clear and thoroughly test all the possible Wildcard Patterns.
- Your new unit tests run and pass when you run `make test` or `make pr` from the siglens base directory
-  If adding comments to your code makes it easier to understand, you should add them. If the code is already self-explanatory, you can skip them
- Running `make pr` gives no errors

**Comment by SergeyPishchulov** [comment]
I'd like to take this task.
Will it be ok to place unit tests on wildcard somewhere [here](https://github.com/siglens/siglens/blob/7efab8f2d9255f4fe56f288f9f9212ece3cd1732/pkg/segment/segexecution_test.go#L165)?

**Comment by SergeyPishchulov** [comment]
My plan is ingest some data, then call [ParseAndExecutePipeRequest](https://github.com/siglens/siglens/blob/b1a80e2d8454b8faf955954fa56593ef9bc43f32/pkg/ast/pipesearch/searchHandler.go#L240C6-L240C32) and check that in results we see only those logs that we expected.

Could you tell me how to ingest some data in the test? Couldn't find it in any other tests.

**Comment by AndrewHess** [comment]
For ingesting specific test data, we use sigclient: https://github.com/siglens/siglens/tree/develop/tools/sigclient

For our end-to-end tests (in ingest.csv and restart.csv) we use benchmark data that you can ingest like this (from the `sigclient` directory)
```
go run main.go ingest esbulk -n 10 -g benchmark -d http://localhost:8081/elastic -t 100_000
```
You can see exactly how we're running the end-to-end tests here: https://github.com/siglens/siglens/blob/develop/.circleci/config.yml

You can also ingest some sample test data by going to the UI (localhost:5122) -> Ingestion -> Send Test Data. But I think that data will be different than what we use for end-to-end testing
