### ISSUE TITLE
UI : Show Alerts Associated with Contact Point in Delete Confirmation Popup

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#104]
# Description:
When attempting to delete a contact point, we want to enhance the confirmation popup to include a button or text that allows users to view all alerts associated with the contact point.

# Changes:

1. Add a button or text in the confirmation popup: "View alerts associated with this contact point."
2. When the user clicks on the button or text, display a scrollable container within the same popup showing all alerts associated with the contact point.

### Confirmation Popup:
```
Cannot delete contact point 

The contact point named 'ContactPointName' is currently in use by multiple alerts.

[View alerts associated with this contact point]   [Close]
```

### On Clicking "View alerts associated with this contact point":
```
[Alert 1]
[Alert 2]
[Alert 3]
[...]
```

#### Utilize the `getAllAlertsWithSameContactPoint` function from `contact.js` to retrieve the alerts associated with contact point.

ScreenShot: 
<img width="1434" alt="image" src="https://github.com/siglens/siglens/assets/71771131/bbdc0240-0774-4139-8040-d7030ea8eb9a">

**Comment by PratikshaPatil77** [comment]
I want to work on this .

**Comment by sunitakawane** [comment]
Please go ahead.
