### ISSUE TITLE
UI : Colored Backgrounds for Alert States

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#106]
# Description:
We want to add colored backgrounds for different states of alerts. 

# Expected Behavior:
Normal State: Green background. (#53DB6E)
Firing State: Red background. (#F55759)
Pending State: Yellow background. (#F4BB20)

### Changes:
Add colored backgrounds to the alert states in the alert table.
Implement the same color scheme for alert states in the alert details view.

# Reference Screenshot:
<img width="137" alt="image" src="https://github.com/siglens/siglens/assets/71771131/96ffab2a-44e7-4316-b0a6-0f25441c5160">

**Comment by pranavk1511** [comment]
I would like to work on this

**Comment by pranavk1511** [comment]
How do i trigger alerts to test them ?

**Comment by ChinmayDharwad24** [comment]
I would like to work on this

**Comment by pranavk1511** [comment]
I have created a PR . Kindly review it

**Comment by shraddha-7896** [comment]
"I want to work with you".

**Comment by nbhavana** [comment]
sure go ahead

**Comment by nbhavana** [comment]
> I have created a PR . Kindly review it

we will review the PR asap

**Comment by ChakradharAbhinay** [comment]
i want to work on this

**Comment by nkunal** [comment]
go ahead
