### ISSUE TITLE
[STORY] Use space-efficient sets to track metrics cardinality

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#1079]
# Description
https://github.com/siglens/siglens/pull/1044 added some APIs for metrics cardinality. However, some of those APIs are making large sets to count the number of unique series (TSIDs), and if there's ~1 billion series, that will take a lot of RAM. Instead, we should use a bloom filter or HyperLogLog (HLL) structure to get an estimate of the number of series in a more space-efficient manner. There's examples of bloom filters and HLL elsewhere in the repo.

# (Optional) Testing
Describe how this should be tested and/or which files unit tests should be added to.

For documentation changes or other similar scenarios, this section can be deleted.

# Acceptance Criteria
The APIs still give relatively accurate estimates, but use much less RAM when there's ~1 billion series

**Comment by dongrep** [comment]
Can I work on this? 

If yes, could we connect to understand where I can find the filters or HLL examples and how could I get to ~1 billion series

**Comment by AndrewHess** [comment]
yYou can ingest metrics data like this: https://github.com/siglens/siglens/blob/develop/.circleci/config.yml#L37 There's more info about the various flags in the sigclient readme: https://github.com/siglens/siglens/tree/develop/tools/sigclient

Here's en example where we setup a bloom: https://github.com/siglens/siglens/blob/develop/pkg/segment/query/metadata/metricsmetadata.go#L86
Here's an example of using HLL (we just switched the library, so if you use HLL, use the one added in this PR): https://github.com/siglens/siglens/pull/1523

**Comment by dongrep** [comment]
@AndrewHess I have raised a PR and left comments on it. Let me know once you see them.
