### ISSUE TITLE
UI : Replace Log Search Icon in Side Navbar

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#108]
# Description:
Replacing the current log search icon in the side navbar. 

# Provided SVG Icons:
#### Active Icon : 
![Search Icon Active](https://github.com/siglens/siglens/assets/71771131/085fa626-87bb-4f5e-b5b1-9d6eb6b87deb)
 
#### Inactive Icon : 
![Search Icon Inactive](https://github.com/siglens/siglens/assets/71771131/f0b63a9a-294b-44a9-b5c0-68037ef44b87)

**Comment by kaushik-manivannan** [comment]
I would like to work on this issue.
