### ISSUE TITLE
[STORY] SPL: Allow the use of the eval command in non-groupby queries.

### ISSUE THREAD

**Issue by Jiale-Fang** [siglens/siglens#1089]
# Description
eval cmd: https://docs.splunk.com/Documentation/SCS/current/SearchReference/EvalCommandExamples
Currently, we only support using `eval cmd` for `group by` queries. For example:
- city=Boston | stats count AS Count `BY http_status` | eval abs=abs(http_status - 1000)
- city=Boston | stats count AS Count `BY http_status` | eval ceil=ceil(http_status - 1000)

You should get it work for all the types of queries, e.g.:
- city=Boston | eval abs=abs(http_status - 1000)

# (Optional) Testing
Describe how this should be tested and/or which files unit tests should be added to.

For documentation changes or other similar scenarios, this section can be deleted.

# Acceptance Criteria
List the concrete items that should be completed for this task to be considered completed. Be as clear and thorough as you can.

**Comment by saniya16** [comment]
I would like to work on this

**Comment by AndrewHess** [comment]
Great, go for it
