### ISSUE TITLE
[STORY] Refactor Spl Stats Functions

### ISSUE THREAD

**Issue by Jiale-Fang** [siglens/siglens#1103]
# Description
In `spl.peg` file, stats functions share a lot of similarities. And we have 20-30 plus functions parsing by this way. You should create a general method to remove redundant code. 
https://github.com/siglens/siglens/blob/20f25abf1899d96e45a99bbbc92e4db6a7664e6b/pkg/ast/spl/spl.peg#L2133-L2203

# (Optional) Testing
doc: https://pkg.go.dev/github.com/mna/pigeon#section-readme
```
go get -u github.com/mna/pigeon	//Download library
pigeon -o pkg/ast/spl/spl.go pkg/ast/spl/spl.peg 
```
# Acceptance Criteria
List the concrete items that should be completed for this task to be considered completed. Be as clear and thorough as you can.

**Comment by saniya16** [comment]
I would like to work on this

**Comment by AndrewHess** [comment]
Great, go ahead

**Comment by deva-rushi** [comment]
I will be working on it

**Comment by AndrewHess** [comment]
Sorry, there's actually an open PR already for this

**Comment by deva-rushi** [comment]
It’s ok, are there any other issues that I can work on?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AtharvaKeshre** [comment]
I will be working on it

**Comment by Dhruv1681** [comment]
I will be working on it

**Comment by Macbeth98** [comment]
Sorry @Dhruv1681 @AtharvaKeshre , there is already a PR out for this, please choose another Issue. Thanks!
