### ISSUE TITLE
[NEW]  Make builder vs code as a setting

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#1110]
# Description
By default when a user visits the log search page, the Query Builder is showed. If a user wants to have editable queries (code) then they have to click on it everytime. Make this setting confiurable. Once can click on the gear icon, and choose what default mode they want for log-search: builder and code. This setting must be preserved across multiple query searches

# Benefits
Describe why you want this feature.

# (Optional) Possible Implementation
If you have any ideas on how this should be implemented, let us know here.

# (Optional) Additional Context
Add anything else we should know about this.

**Comment by sunitakawane** [comment]
fixed by #1121
