### ISSUE TITLE
[BUG] Alert detail page doesn't show full information for metrics alert type

### ISSUE THREAD

**Issue by bernatixer** [siglens/siglens#1196]
# Description
The alert details page doesn't show the full information for metrics type.

# Steps to Reproduce
1. Create a metrics alert
2. Go to the created alert details page

# Expected Behavior
The page shouls show all the details 

# Environment
- **SigLens Version:** 0.2.19
- Running on Linux

# Additional Context
Metric alert details page:
![image](https://github.com/siglens/siglens/assets/2202231/67420ee2-2538-4af7-8a4d-55a492927ddf)

Metric alert edit page:
![image](https://github.com/siglens/siglens/assets/2202231/57ba1fc1-603c-4ca0-9b49-ab3e9bfe6aab)

Example of a logs alert:
![image](https://github.com/siglens/siglens/assets/2202231/5692de08-9126-47cd-9fc2-9ab625b5c64c)

**Comment by nkunal** [comment]
@Divyanshu11011 please add this to your list

**Comment by Divyanshu11011** [comment]
@nkunal Will get Resolved !
