### ISSUE TITLE
Add "Copy" Icon for JSON Config in Dashboard Settings Page

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#126]
# Description
Include a "Copy" icon for users to easily copy the JSON.

**Comment by kashmii** [comment]
I would like work on this.

**Comment by nkunal** [comment]
Fantastic!

**Comment by sonamgupta21** [comment]
1.Yes, when the user hovers over the 'Copy' icon, the tooltip should show 'Copy.' When the user clicks, and the JSON gets copied, the tooltip should display 'Copied!'.
<img width="123" alt="image" src="https://github.com/siglens/siglens/assets/71771131/f2d62412-f794-42fa-89ca-5a39967f2c03">

<img width="110" alt="image" src="https://github.com/siglens/siglens/assets/71771131/e2ebcf8f-4825-44a6-93ec-267280be8fac">

2. Placement of icon - 
<img width="731" alt="image" src="https://github.com/siglens/siglens/assets/71771131/bf92f32c-6c67-41a9-a564-6ce7ec5609da">

You can find the copy icon in static/asessts folder for both light and dark mode.
