### ISSUE TITLE
SPL: timechart with aggregate

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#127]
# Description
Creates a chart showing the specified aggregate per time bin, and the aggregate can contain a BY clause to overlay a series for each distinct combination of the BY fields values.
https://docs.splunk.com/Documentation/Splunk/9.1.0/SearchReference/Timechart

timechart can also be used with an eval expression instead of an aggregate, but that's not covered by this issue.

Example
I think that for something like
```
timechart span=1m count by instance
```
the data should be something like
```
bin _time span=1m | count BY _time, instance
```
but then the data will have to be rendered into a chart.

# Testing
### Ingesting Data
To ingest some fake data into siglens for testing. Clone https://github.com/sigscalr/sigscalr-client and then from within that repo run
```
go run main.go ingest esbulk -t 10_000 -d http://localhost:8081/elastic --processCount 1 -n 1 -b 500 -g dynamic-user
```
while siglens is running. You can also run
```
go run main.go ingest esbulk -n 10 -g benchmark -d http://localhost:8081/elastic -t 100_000
```
to ingest the data that is used for the CICD tests. You can clear the `siglens/data/` folder to remove all the data from siglens (you should probably do this only when siglens is not running).

### Querying data
After ingesting some data, you can run some basic manual tests in the siglens UI. 

## Unit Testing
* Add unit tests to `splParser_test.go` to ensure that this command gets parsed correctly.
* Add CICD tests in `cicd/ingest.csv` and `cicd/restart.csv`

**Comment by darshannere** [comment]
Can I work on this?

**Comment by nkunal** [comment]
yes go ahead

**Comment by Macbeth98** [comment]
This issue is completed with PRs: #291 and #311
