### ISSUE TITLE
SPL: sort: sort with limit

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#128]
# Description

https://docs.splunk.com/Documentation/Splunk/9.1.0/SearchReference/Sort

When no limit is provided, use 10000. When 0 is the limit, return all results.

# Testing
### Ingesting Data
To ingest some fake data into siglens for testing. Clone https://github.com/sigscalr/sigscalr-client and then from within that repo run
```
go run main.go ingest esbulk -t 10_000 -d http://localhost:8081/elastic --processCount 1 -n 1 -b 500 -g dynamic-user
```
while siglens is running. You can also run
```
go run main.go ingest esbulk -n 10 -g benchmark -d http://localhost:8081/elastic -t 100_000
```
to ingest the data that is used for the CICD tests. You can clear the `siglens/data/` folder to remove all the data from siglens (you should probably do this only when siglens is not running).

### Querying data
After ingesting some data, you can run some basic manual tests in the siglens UI.
e.g. `* | sort 100 city`
## Unit Testing
* Add unit tests to `splParser_test.go` to ensure that this command gets parsed correctly.
* Add CICD tests in `cicd/ingest.csv` and `cicd/restart.csv`

**Comment by girish332** [comment]
Can I work on this?

**Comment by nkunal** [comment]
Yes go ahead

**Comment by darshannere** [comment]
Is there any function to get all the results? or any other implementation from which I can get all results for this issue?

**Comment by Jiale-Fang** [comment]
@darshannere Siglens stores the results by segments. Here is the function you may want to take a look at: `siglens/pkg/segment/reader/recordreader.go` Check out the `GetRecordsFromSegment()` function.

Also, you can see that we use it in `rrcreader.go` to retrieve the raw data

**Comment by nbhavana** [comment]
sure, go ahead
