### ISSUE TITLE
SPL: sort: sort without limit

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#129]
# Description
https://docs.splunk.com/Documentation/Splunk/9.1.0/SearchReference/Sort

Sort on one or more fields, with ties in earlier fields being broken by later fields. Each field can be sorted ascending or descending, and the d or desc flag can be used to reverse the sorting of each specified field.

For now, return all results instead of just the first 10000.

**Comment by anshulsharma1610** [comment]
I can work on this

**Comment by AndrewHess** [comment]
Great, go ahead

**Comment by Jiale-Fang** [comment]
Can i work on this issue?

**Comment by AndrewHess** [comment]
Yep, go for it

**Comment by Jiale-Fang** [comment]
I noticed that our front end sorts response data based on `timestamp` by default. Users have to manually `deselect` 'sort by timestamp' if they want to see the results of the `sort cmd`. I am wondering if I need to provide a flag in resp to indicate that the front end should not sort the result res based on timestamp by default, or if it is good for now?

**Comment by nkunal** [comment]
Providing a flag from backend would be the way to go and then frontend can
decide whether to sort or not

*Best Regards*
*-- Kunal Nawale ,**Founder/CEO, SigScalr*
