### ISSUE TITLE
SPL: bin/bucket: discretize timestamp

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#130]
# Description
https://docs.splunk.com/Documentation/Splunk/9.1.0/SearchReference/Bin
bucket is an alias for bin

bin _time span=5m can be used to make bins spanning 5-minute blocks. This would then be used in a stats or other command grouping by the bin.

SPL allows discretizing on other fields and renaming the field, but for this issue just handle bin _time span=<time-span> with any of the allowed <time-span> values specified in the reference link.

**Comment by Macbeth98** [comment]
This issue is completed with PR: #1246
