### ISSUE TITLE
[STORY] Reduce duplication of functions like Has_blank_InChain

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#1321]
# Description
In segstructs.go, there's a lot of functions like
```
 func (qa *QueryAggregators) HasDedupBlock() bool {...}
```
followed by something like:
```
func (qa *QueryAggregators) HasDedupBlockInChain() bool {
	if qa == nil {
		return false
	}

	if qa.HasDedupBlock() {
		return true
	}
	if qa.Next != nil {
		return qa.Next.HasDedupBlockInChain()
	}
	return false
}
```

You should make a higher-level version of this `InChain()` function so that we can do something like:
```
func (qa *QueryAggregators) HasDedupBlockInChain() bool {
    return qa.hasInChain(qa.HasDedupBlock)
}
```
And then also change all the `Has_blank_InChain()` functions to use your new function

# Testing
segstructs_test.go has some unit tests for these functions. Add more as needed.

# Acceptance Criteria
- You make the `qa.hasInChain()` function (you can name it differently if you find a better name)
- You replace all the `Has_blank_inChain()` functions to call your new function
- You add any unit tests if needed
- All the tests pass

**Comment by SergeyPishchulov** [comment]
I would like to work on this

**Comment by AndrewHess** [comment]
Cool, go ahead
