### ISSUE TITLE
Mark dashboards as favorites.(Backend)

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#151]
# Description 
Implement backend functionality to support marking dashboards as favorites. 
Introduce a boolean attribute, such as isStarred, in the dashboard JSON to reflect the favorite status.

**Comment by ShubhiMiradwalNEU** [comment]
I want to work on it

**Comment by nkunal** [comment]
Fantastic! Please go ahead

**Comment by Pranav014** [comment]
I want to work on it

**Comment by kskeerthana** [comment]
I want to work on it

**Comment by swethapaturu9** [comment]
I want to work on it

**Comment by nbhavana** [comment]
> I want to work on it

I have assigned this issue to you

**Comment by venkateshamatam** [comment]
Is anyone working on this? If not, I would like to pick it up! Thank you!

**Comment by nbhavana** [comment]
@venkateshamatam the task has been assigned to someone in queue, if they don't work on it in next two days, it will be assigned to the next person in request queue

**Comment by venkateshamatam** [comment]
Sure @nbhavana, looking forward!

**Comment by nbhavana** [comment]
@swethapaturu9 are you still interested to work on this issue?

**Comment by swethapaturu9** [comment]
yes @nbhavana ,  I would like to work on this !

**Comment by nbhavana** [comment]
@swethapaturu9 we just received a PR for this issue. Is there some other issue you would like to work on?

**Comment by swethapaturu9** [comment]
@nbhavana , I have been working on this for some time and I did integrate UI and backend , could I make a PR on my implementation of this issue ?
