### ISSUE TITLE
 Display Recent or Starred Dashboards at the Top

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#152]
Dependency on `https://github.com/siglens/siglens/issues/151`

**Comment by PratikshaPatil77** [comment]
I want to work on this.

**Comment by NagarjunMa** [comment]
Could you please give me more information on how this must be implemented? 
The starring feature does not appear to be functioning on the website.

**Comment by swethapaturu9** [comment]
@nbhavana , I would like to work on this issue !

**Comment by nbhavana** [comment]
This issue is ready to be worked on now, the backend work for this is done.

**Comment by PratikshaPatil77** [comment]
If no one is working on this issue, I would like to work on this issue.
