### ISSUE TITLE
[STORY] Add unit tests for Number

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#1534]
# Description
https://github.com/siglens/siglens/pull/1528 added a `Number` type. Add unit tests for it.

# Acceptance Criteria
- All your unit tests pass
- You've tested setting and getting values
- You've tested some error cases
- You've tested `ReduceFast`
- You've added any other tests that you think are necessary

**Comment by dongrep** [comment]
Can I work on this?

**Comment by AndrewHess** [comment]
Yeah go for it!

**Comment by dongrep** [comment]
Is there a reference to how I could match test standards?

**Comment by AndrewHess** [comment]
Yeah, here's some examples:
- https://github.com/siglens/siglens/blob/develop/pkg/utils/option_test.go
- https://github.com/siglens/siglens/blob/develop/pkg/utils/maputils_test.go
- https://github.com/siglens/siglens/blob/develop/pkg/utils/bitutils_test.go

Then to run the tests, running `make test` will run the whole test suite, or you can do something like:
```
go test ./pkg/utils
```
to run only the tests in the utils package

**Comment by dongrep** [comment]
Great thank you. Will get started.

**Comment by dongrep** [comment]
@AndrewHess I have added tests and submitted pr for review.
