### ISSUE TITLE
[STORY] Consolidate addToBlockBloomBothCases , addToBlockBloomBothCasesWithBuf

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#1591]
# Description
Consolidate addToBlockBloomBothCases , addToBlockBloomBothCasesWithBuf

#<issue-number>.

# (Optional) Testing
Describe how this should be tested and/or which files unit tests should be added to.

For documentation changes or other similar scenarios, this section can be deleted.

# Acceptance Criteria
List the concrete items that should be completed for this task to be considered completed. Be as clear and thorough as you can.

**Comment by AndrewHess** [comment]
This ended up getting done as part of the original PR: https://github.com/siglens/siglens/pull/1577
