### ISSUE TITLE
[BUG] Fields command returning all columns in the websocket/API response

### ISSUE THREAD

**Issue by vasukalariya** [siglens/siglens#1713]
# Description
Clearly describe the bug and how to reproduce it. If applicable, include screenshots.

Fields command is returning all columns in the websocket/API response.

Response
<img width="953" alt="image" src="https://github.com/user-attachments/assets/c3630e7f-e97a-4ad1-b192-ec8e8019f152">

It should only return the relevant fields from the records and not send extra data. Although allColumns is updated, the records itself are not.

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.

- Run this Query: `app_name=Bracecould | eval temp_value = 1 | fields app_name, first_name, last_name, temp_value`.
- Monitor the response in network tab or send an API request with this query to the HTTP client.

# Expected Behavior
Clearly describe what you expect to happen.

Only the filtered columns should be present in the response. 

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by Macbeth98** [comment]
This issue is fixed.
