### ISSUE TITLE
Alert History Table (with state changes, config changes) 

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#19]
When a user clicks on a specific alert, we should show a tab that shows "History". The history is just chronolgical sequence of:

1. Every time the alert was fired or went normal
2. Any config change in the alert

This table should show 3 columns:

1. Timestamp of the event
2. Event Description (alert fired, alert normal, config change)
3. Username (user who changed the config, or show "system generated" when it is a firing/normal state change

**Comment by shivasaicharanruthala** [comment]
@nkunal  i can work on this. 

I need a clarification on couple of things 
1. how we the user who changed the config as authentication is not implemented yet?  So for now can we hardcode as user modified config as "User Modified" ?
2. Does this ticket needs implementation of both frontend and backend? or backend changes is enough?

**Comment by shivasaicharanruthala** [comment]
Thank you @nbhavana.
