### ISSUE TITLE
[BUG] Reading saved queries

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#198]
# Description
When reading a saved query it uses Splunk as the default query language but when we switch query languages the UI clears the query. So if we save an SQL query, reload it, and switch to SQL, then the query input box will be blank.

# Steps to Reproduce
1. Start siglens
2. In the UI, change the query language to SQL and enter the query
```
SELECT * FROM `ind-0`
```
3. Run the search.
4. Click the "Save Query" button, enter a name, and click the Save button
5. On the left menu bar, click the Saved Queries tab
6. Click on your saved query
7. Switch from Query Builder mode to Free Text mode. You should see the saved query in the search bar, but see Splunk QL as the query language.
8. Switch from Splunk QL to SQL. Now the search bar is empty.

# Expected Behavior
When you reload a saved query, it should use the same query language that it was saved with. It also might be nice to have other things like the index and time range saved with the query.

# Environment
- Commit Hash: 176775e

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by Zhifei-Li** [comment]
1

**Comment by Leelakrishna2091997** [comment]
I would like to work on this.

**Comment by VGARG8** [comment]
I want to wok on it.

**Comment by Hanagojiv** [comment]
I want to work on this

**Comment by nbhavana** [comment]
There is already a PR associated with this issue
