### ISSUE TITLE
[NEW] Make the Save Query error message easier to read

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#199]
# Description
When you save a query but enter a name that is too long and try to save it, you get an error message, but the message is small and hard to read.

The error message here is `Length of queryname must be between 3 and 16.`
<img width="451" alt="Screenshot 2023-12-07 at 11 59 51" src="https://github.com/siglens/siglens/assets/20426590/314c1985-9fb8-4627-a9e7-b6153fa8dab1">

# Steps to Reproduce
1. Start siglens
2. In the UI, enter a query and run the search
3. Click the Save Query button
4. Enter a name that is too short (less than 3 characters) or too long (more than 16 characters)
5. Click Save. You should see an error message.

# Benefits
Error messages should be easy to read.

# (Optional) Possible Implementation
If you have any ideas on how this should be implemented, let us know here.

# (Optional) Additional Context
Also `queryname` should probably be `query name`. And it would be nice to allow names longer than 16 characters. Also when implementing this, you should check that it looks good in dark mode as well

**Comment by Zhifei-Li** [comment]
1

**Comment by divyakasa-09** [comment]
I want to work on it

**Comment by nbhavana** [comment]
@divyakasa-09  This issue already has a PR associated with it and its in review.
