### ISSUE TITLE
DataDog Ingest Interface

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#20]
Implement DataDog ingestion method. Existing DD users can just point their DD agent to SigLens and SigLens must be able to ingest their logs/events/metrics

**Comment by shivasaicharanruthala** [comment]
@nkunal  can you share more info on which pkg in siglens I need to go through so that I can able to contribute for this issue

**Comment by nbhavana** [comment]
@shivasaicharanruthala This issue is not very well define, when we have an accurate description of this ticket , we will recreate it
