### ISSUE TITLE
[BUG] LIMIT not working in SQL

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#201]
# Description
When you run an SQL query with `LIMIT <number>` to limit the results, it seems to ignore the limit and display all results anyways. I haven't tested this with a groupby request.

# Steps to Reproduce
1. Start siglens
2. Ingest some data. For example (with `sigscalr-client`):
```
go run main.go ingest esbulk -t 10_000 -d http://localhost:8081/elastic --processCount 1 -n 5 -b 500 -g dynamic-user
```
3. Go to the UI, choose a Free Text SQL query, and enter
```
SELECT * FROM `*` LIMIT 10
```
You'll see that you get more than 10 results.

# Expected Behavior
With that query, exactly 10 results should be shown.

# Environment
- Commit Hash: e3a815b

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by XuanhaoZu** [comment]
I want to work on it

**Comment by prathameshwalinu** [comment]
I want to work on it

**Comment by nkunal** [comment]
Please go ahead

**Comment by prathameshwalinu** [comment]
I want to work on it

**Comment by VGARG8** [comment]
i want to work on it

**Comment by ChinmayDharwad24** [comment]
I want to work on this

**Comment by nikhil-enni** [comment]
I want to work on this

**Comment by nbhavana** [comment]
> I want to work on it

I have assigned the issue to you. You can start working on it

**Comment by nbhavana** [comment]
> i want to work on it

Currently this task is assigned. We usually give 3 days for them to work on it. If there is no progress in 3 days, we assign it to the next person in the queue  to work on it.

**Comment by nbhavana** [comment]
> I want to work on this

Currently this task is assigned. We usually give 3 days for them to work on it. If there is no progress in 3 days, we assign it to the next person in the queue  to work on it.

**Comment by nbhavana** [comment]
> I want to work on this

Currently this task is assigned. We usually give 3 days for them to work on it. If there is no progress in 3 days, we assign it to the next person in the queue  to work on it.

**Comment by Hanagojiv** [comment]
I want to work on this.

**Comment by nbhavana** [comment]
@XuanhaoZu Currently this task is assigned. We usually give 2 days for them to work on it. If there is no progress in 3 days, we assign it to the next person in the queue to work on it.

**Comment by padekars** [comment]
I want to work on this

**Comment by nbhavana** [comment]
Currently this task is assigned. We usually give 2 days for them to work on it. If there is no progress in 3 days, we assign it to the next person in the queue to work on it.

**Comment by nbhavana** [comment]
@VGARG8 I have assigned this task to you
