### ISSUE TITLE
[BUG] Changing dashboard name requires refresh

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#203]
# Description
When you change the name of a dashboard and go back to the dashboard, it displays the old dashboard name until you refresh the page.

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. Run siglens
2. In the UI, on the left menu bar, click the Dashboards panel
3. Click the New Dashboard button and name the dashboard MyDashboard and click Save
4. Click the Gear button to edit the dashboard
5. Change the name to MyDashboard123 (you'll see the dashboard name changing in the top left of the page) and click Save
6. After clicking Save, in the top left you'll see
```
All Dashboards > MyDashboard
```
but once you refresh the page you'll see
```
All Dashboards > MyDashboard123
```
Also, if you just click the Refresh Dashboard button, it doesn't refresh the name; you have to actually refresh the tab in your browser

# Expected Behavior
After saving the new dashboard name, the new name should appear as soon as you return to the dashboard. You shouldn't have to refresh the page

# Environment
- Commit Hash: e3a815b
- Browser: Chrome

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by venkateshamatam** [comment]
Can I take this up?

**Comment by AndrewHess** [comment]
Yep!
