### ISSUE TITLE
Hover on Dashboard and show what query is behind it

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#21]
Hover on a dashboard Panel and show what query is behind it

**Comment by nkunal** [comment]
@KalePallavi you can work on this one.

**Comment by PratikshaPatil77** [comment]
If nobody is working on this problem, I'd like to take up the task.

**Comment by PratikshaPatil77** [comment]
If nobody is working on this problem, I'd like to take up the task.

**Comment by nbhavana** [comment]
I have assigned the issue to you

**Comment by KalePallavi** [comment]
Yes
