### ISSUE TITLE
Dashboard save : do not allow empty string or space as dashboard name

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#212]
# Description
Currently when new dashboard is created , or old dashboard is updated, we can enter space as dashboard name. This should not be allowed.

On UI side, before calling api to create/update dashboard,  trim dashboard name , and check if it is empty, show error / popup is dashboard name is empty.

**Comment by PratikshaPatil77** [comment]
I want to work on this.

**Comment by sunitakawane** [comment]
Please go ahead.

**Comment by Ishita1022** [comment]
I want to work on this.

**Comment by ChinmayDharwad24** [comment]
I want to work on this

**Comment by Leelakrishna2091997** [comment]
I would like to work on this.
