### ISSUE TITLE
UI error in the browser : "Too big request header" 

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#213]
[#](url) Description
If we do not open siglens UI in incognito window , `"Too big request header" ` error shows up in the browser.
It's a cookie error.  Chrome has a limit on request header size.

# Expected Behavior
We should be able to open siglens html pages without opening it in in incognito window

Can be resolved by fixing the size of the cookies which we create.

# Environment

- Browser : chrome

# (Optional) Additional Context
Check this link to follow the discussion about this issue on slack community:
[Add anything else we should know about this problem.
](https://siglens-community.slack.com/archives/C063KMTGN1H/p1701220653468469?thread_ts=1700616120.497469&cid=C063KMTGN1H)

![Screenshot 2023-11-21 at 8 35 10 PM](https://github.com/siglens/siglens/assets/6307537/0c9dde31-bce1-4ad2-91f2-66ff6b4d1e1d)
![Screenshot from 2023-11-28 20-16-21](https://github.com/siglens/siglens/assets/6307537/1de2c691-c194-4b39-84b2-60f9b66a7ad9)
[requestHeader.txt](https://github.com/siglens/siglens/files/13742275/requestHeader.txt)

**Comment by Ishita1022** [comment]
I want to work on this.

**Comment by nkunal** [comment]
Yea go ahead

**Comment by pranitb10** [comment]
Hi, could someone from the team please provide more information on this and how to reproduce this issue? That would be a great help to start working on this either for me or someone else. Thank you in advance!

**Comment by nbhavana** [comment]
> Hi, could someone from the team please provide more information on this and how to reproduce this issue? That would be a great help to start working on this either for me or someone else. Thank you in advance!

Thank you for pointing out , we will get back to you asap.

**Comment by nbhavana** [comment]
@pranitb10 There are no steps to reproduce this issue. I have added some screen shots and link of discussion about this issue on slack to get more context.  It's a cookie error.  Chrome has a limit on request header size. I think for now reducing the size of cookies that we create should help to resolve this issue.
