### ISSUE TITLE
[BUG] Unable to add a panel to an existing dashboard

### ISSUE THREAD

**Issue by venkateshamatam** [siglens/siglens#221]
Description
When you try to add a panel to an existing dashboard with no panels, it logs a warning on the console and does not add the panel to the dashboard. However, it works fine if you add a create a new dashboard and add a panel through the same dialog box.

![image](https://github.com/siglens/siglens/assets/113487319/30ae56a0-f93b-4762-aac4-eac98426a272)

Steps to Reproduce
Create a new dashboard manually without adding any panels.
Query some logs and try to add a panel to the existing dashboard you just created.
See the warning on the console and it doesn't add the panel. (Note that it may work if you already have panels on the existing dashboard)

Expected Behavior
Should be able to add a panel to the existing dashboard with no warning in the console.

Environment
Chrome

**Comment by venkateshamatam** [comment]
I would like to work on this bug

**Comment by rakshitsoni05** [comment]
I would like to work on it

**Comment by Leelakrishna2091997** [comment]
I would like to work on this issue.

**Comment by nbhavana** [comment]
> I would like to work on it

This issue is already assigned.

**Comment by nbhavana** [comment]
> I would like to work on this issue.

This issue is already assigned.
