### ISSUE TITLE
[BUG] Handling Creation of Multiple Dashboards with the Same Name

### ISSUE THREAD

**Issue by venkateshamatam** [siglens/siglens#223]
# Description
We are able to create multiple dashboards having the same name, the current logic does not check for the uniqueness of the dashboard name while creating the dashboard. 
![image](https://github.com/siglens/siglens/assets/113487319/7e7d48ee-bb66-4244-b152-0ff82a83a6f9)

# Steps to Reproduce
Create a new dashboard with a certain name.
Create another or multiple such dashboards with the same name.
Hit the /listall API to verify the creation of these dashboards, note that they have the same name but different dashboard IDs.

# Expected Behavior
Should not allow the creation of multiple dashboards with the same name.

**Comment by venkateshamatam** [comment]
I would like to work on this issue!

**Comment by nkunal** [comment]
Fantastic! Please go ahead

**Comment by Leelakrishna2091997** [comment]
I would like to work on this issue.

**Comment by sameerdawani97** [comment]
I wan to work on this.

**Comment by dineshpabbati** [comment]
I want to work on this
