### ISSUE TITLE
[BUG] Dashboard Settings Page Not Reflecting Updated Data

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#226]
# Description
After updating a dashboard from the dashboard settings page and saving the changes, returning to the settings page shows the previous data instead of the updated information.

# Steps to Reproduce
1. Create a new dashboard.
2. Go to the setting page, and update the information (name or description).
3. Save the changes.
4. Go back to the settings page again. 

# Expected Behavior
Dashboard Settings should reflect the updated information.

**Comment by NagarjunMa** [comment]
I would like to work on it

**Comment by Pranav014** [comment]
I want to work on it
