### ISSUE TITLE
[BUG] The selected time picker from the dropdown is not reflected in the request payload for all query languages

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#250]
# Description
When you try to query logs with  `SpunkQL`, `SQL` or `Log QL` with any time from the time picker window, the time selected is not reflected correctly in the request payload. It always sends `Last 24hrs` for both `Query Builder` and `Free Text` options.

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. Go to logs page, select `Query Builder` or  `Free Text` , select ``SpunkQL` as query language, select any time from the time picker dropdown.
2. Now type the query in search box or build the query using query builder and hit search button.
3. Now, in Developer tools, go to the network tab and look for the search request. Check the payload and you will see that the start epoch is always `now-24h`. Check this screen shot 
<img width="1498" alt="image" src="https://github.com/siglens/siglens/assets/6307537/cf4e0bc4-13c0-4fcd-9c46-34d6840aa0a8">
Here you can see that the time selected is `Last 5Mins` but the request payload sends `now-24h`

<img width="1497" alt="image" src="https://github.com/siglens/siglens/assets/6307537/7eb44f41-0d66-4f37-b420-a731f59a1568">

# Expected Behavior
The time selected in the time picker should be reflected in the request payload.

**Comment by pranitb10** [comment]
Hello! I would like to work on this. Can you please assign it to me?

**Comment by nbhavana** [comment]
yes, go ahead

**Comment by pranitb10** [comment]
Thank you for assigning it to me @nbhavana
