### ISSUE TITLE
[BUG] Misleading capitalization for columns

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#258]
# Description
When we show columns in the UI, all of them are lowercase, even if the data was ingested with an uppercase field name. However, when we query the data we have to use the correct case (the case it was ingested as), so it can be hard sometimes to know what the correct capitalization is.

For example, in the below image there's a query on `VendorID`, which works correctly
<img width="1343" alt="image" src="https://github.com/siglens/siglens/assets/20426590/0eadf484-52c3-40f2-b115-71f05498c8a8">
But in the below image there's a query on `vendorid` and no data is returned because that column with that capitalization doesn't exist
<img width="1343" alt="image" src="https://github.com/siglens/siglens/assets/20426590/3a042151-b64c-42fd-868e-d2278b90844a">

# Steps to Reproduce
1. Ingest some data where the column name has capital letters
2. Open the UI
3. Run a search on the capitalized column.

# Expected Behavior
The UI should show the column name with the correct capitalization, so I can type it verbatim into the query input box and it will have the correct capitalization

# Environment
- Commit Hash: c40a902

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by venkateshamatam** [comment]
I can take this up, we are converting the headerName to lowercase explicitly while rendering the dashboard.

**Comment by AndrewHess** [comment]
Yep go ahead

**Comment by venkateshamatam** [comment]
@AndrewHess, I've created a PR to fix this bug - #259
