### ISSUE TITLE
[UI] Add info icon for on alerts page for add contact points for channel id and slack token

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#260]
# Description
Add info icon to on alerts page for  add contact points for channel id and slack token.
# Benefits
This will easy for user who is adding contact points. They will know what channel id and slack token looks like.

<img width="1506" alt="image" src="https://github.com/siglens/siglens/assets/6307537/2e266d8c-e4a4-4807-a3ea-9c0ac0390448">

**Comment by PratikshaPatil77** [comment]
I want to work on this issue.

**Comment by nbhavana** [comment]
Refer this [article](https://help.socialintents.com/article/148-how-to-find-your-slack-team-id-and-slack-channel-id) to see sample slack id and channel id
