### ISSUE TITLE
[STORY]  Fix the misspells as reported below

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#264]
# Description
Clearly describe the task. Break it down as much as you can so it's easier to implement. Link to existing issues if appropriate using #<issue-number>.
Take a look at this report : https://goreportcard.com/report/github.com/siglens/siglens

1. And fix all of the misspells reported under the section `misspell`

# (Optional) Testing
Describe how this should be tested and/or which files unit tests should be added to.

go to https://goreportcard.com/report/github.com/siglens/siglens
and in the search bar 
<img width="603" alt="image" src="https://github.com/siglens/siglens/assets/604069/f1685439-438a-47e2-a4db-bc5106eef95d">

enter your repo after you have pushed changes to your fork. for e.g.:  github.com/<your_git_username>/siglens

For documentation changes or other similar scenarios, this section can be deleted.

# Acceptance Criteria
List the concrete items that should be completed for this task to be considered completed. Be as clear and thorough as you can.

The above go report card should show no misspells for your fork.

**Comment by KarthikMalasani** [comment]
I would like to work on this!

**Comment by nbhavana** [comment]
great, go ahead. I have assigned it to you
