### ISSUE TITLE
[STORY] Switch to using docker compose

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#268]
# Description

Currently we use docker cmd to run the siglens container. Switch to using docker compose file. Refer online to see how to create docker compose files

# (Optional) Testing
Make sure the docker compose cmd works on various OSs (mac, linux)

# Acceptance Criteria
1. All readme content replaced to use docker compose
2. install_with_docker.sh script updated to use docker compose

**Comment by shivasaicharanruthala** [comment]
can I work on it?

I have a quick question, Do docker compose file need to 2 services one for the backend and other for the UI client  so need to refactor the code to start the UI client and backend server independently  and update the **install_with_docker.sh** script to use docker compose file. Is my approach right?

**Comment by nkunal** [comment]
Go ahead !

Backend and frontend are run inside the same binary so dont need to run them separately in compose

**Comment by shivasaicharanruthala** [comment]
@nkunal Then why do we actually moving to docker compose if its a single binary running both services? May I know its just the singlebinary we need to move to docker compose or does it have any other services ?

**Comment by nkunal** [comment]
in future it will have other services plus the resource allocation (local disk) across restarts becomes easy

**Comment by shivasaicharanruthala** [comment]
okay now it make sense for me
