### ISSUE TITLE
[BUG] Available Fields background color is truncated

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#274]
# Description
When selecting Available Fields in the UI, long field names are not showing up properly
<img width="1293" alt="image" src="https://github.com/siglens/siglens/assets/20426590/b9894da5-0685-4faf-ac65-e06f0aa2c49d">
<img width="1293" alt="image" src="https://github.com/siglens/siglens/assets/20426590/e5517994-375c-493f-ac05-b2efa29f1b4c">

# Steps to Reproduce
1. Ingest some data with long column names. You can put
```
{"DOLocationID":236,"PULocationID":140,"MyLongNamedColumn.Extra.Final.V2":1,"VendorID":1}
{"DOLocationID":140,"PULocationID":237,"MyLongNamedColumn.Extra.Final.V2":1,"VendorID":1}
{"DOLocationID":237,"PULocationID":140,"MyLongNamedColumn.Extra.Final.V2":1,"VendorID":1}
```
into a file, then use the `ingester.py` from https://github.com/siglens/siglens-docs/blob/main/docs/benchmarks/benchmark-runbook.md to ingest the data into siglens
2. Open the UI
3. Click on the Available Fields dropdown

# Expected Behavior
The background color for each field should extend to the end of the column name

# Environment
- Commit Hash: a8e1e13

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by nkunal** [comment]
Go ahead
