### ISSUE TITLE
Add username & password ingestion auth option

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#29]
A design doc is in progress and will be linked here.
Should update config to enable basic auth for all requests

**Comment by shivasaicharanruthala** [comment]
Hi @AndrewHess, Is there any design doc available for this issue? I want to work on this

**Comment by AndrewHess** [comment]
Not yet

**Comment by shivasaicharanruthala** [comment]
@AndrewHess  when the docs is ready pls do tag me I want to work on it?
