### ISSUE TITLE
Make the UI url in install_with_docker.sh file clickable

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#304]
# Description
When you install Siglens using the following command: `curl -L https://github.com/siglens/siglens/releases/latest/download/install_with_docker.sh | sh`, once the installation is complete, you will receive a prompt message indicating that the `Frontend can be accessed at http://localhost:5122`. Now the user should simply be able to click on the link `http://localhost:5122` to open the Siglens frontend in your web browser and start using the application.

# Benefits
This feature eliminates the need for users to manually open a new browser tab and type in the URL to access the Siglens user interface (UI). By simply clicking on the provided link, users can effortlessly access the Siglens UI, saving time and effort.

<img width="1110" alt="image" src="https://github.com/siglens/siglens/assets/6307537/5cbe6e53-ecc6-4091-a233-675156e100a9">

**Comment by shivasaicharanruthala** [comment]
@nbhavana  I have raised a PR can you please check that.
