### ISSUE TITLE
Get query port from environment variable

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#31]
Update `GetQueryPort()` in config.go. If the `PORT` environment variable is set, `GetQueryPort()` should return that value. Otherwise, it should return the value of the `queryPort` in the config file (e.g., server.yaml).

**Comment by girish332** [comment]
Hey Can I work on this issue ?

**Comment by AndrewHess** [comment]
Yep!

**Comment by girish332** [comment]
https://github.com/siglens/siglens/pull/39/commits

Kindly review the PR and let me know if you have any changes in mind. I can pick https://github.com/siglens/siglens/issues/14 next after this issue is done

**Comment by AndrewHess** [comment]
Completed by https://github.com/siglens/siglens/pull/39
