### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by shraddha-7896** [siglens/siglens#339]
# Description
Clearly describe the bug and how to reproduce it. If applicable, include screenshots.

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. ...

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by nkunal** [comment]
when creating bugs please describe exactly what the bug is
