### ISSUE TITLE
Add selenium tests for alert pages

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#34]
Similar to how the tests in `selenium-tests/tests` have tests for various pages of our site, we should add tests for the alert pages:
- all-alerts.html
- alert.html
- contacts.html

See the selenium tests readme (which should be added by https://github.com/siglens/siglens/issues/33) for information on getting started with writing selenium tests.

**Comment by shyam2520** [comment]
I have a question regarding the issue (https://github.com/siglens/siglens/issues/34), so similar to the rest of the other test files do you need just check if each element in the UI which is mentioned has the actual text using assert equals,if the number of rows in table is < 1

If so I can take it up (edited)

**Comment by nkunal** [comment]
Yup, it will be very similar to the other tests. Once you have added the tests, you can temporarily change the actual html/js code and remove some element temporarily and see if your new tests catch it.
