### ISSUE TITLE
[BUG] display port bind errors on stdout

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#340]
# Description
When the ports 8081 or 5122 or already bound and then you try to start another instance of siglens via the go run cmd, the stdout displays that it has bound to the ports but actually it has failed. The failure messages show up in siglens.log, along with that we should also print it out on stdout and then exit the process.

these are the errors that show in siglens.log file
```
ESC[31mERROESC[0m[2024-01-04 13:21:06] Failed to start server! Error: cannot bind to "0.0.0.0:8081": address already in use 
ESC[36mINFOESC[0m[2024-01-04 13:21:06] populateMetricsMetadata: reading smFile=data/ingestnodes/kunals-imac.lan.EocRhoFGQrPELBymcJzc97/metricmeta.json 
ESC[36mINFOESC[0m[2024-01-04 13:21:06] Query server has successfully been initialized in 156.458µs 
ESC[31mERROESC[0m[2024-01-04 13:21:06] Failed to start server! Error: cannot bind to "0.0.0.0:5122": address already in use 
```

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. ...

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by freecode23** [comment]
I would like to work on this

**Comment by nkunal** [comment]
Yes please go ahead

*Best Regards*
*-- Kunal Nawale <https://www.linkedin.com/in/kunal-nawale/> ,**Founder/CEO,
SigScalr <https://www.sigscalr.io>*
Blog: SigScalr faster than Elasticsearch by 8x
<https://www.sigscalr.io/blog/sigscalr-vs-elasticsearch.html>
Blog: Petabyte/day of data on 32 machines
<https://www.sigscalr.io/blog/petabyte-of-observability-data.html>
Book a demo  here <https://calendly.com/knawale/30min>

**Comment by smaftoul** [comment]
@freecode23 sorry, I had the issue, didn't took me long to fix it, so I did the PR.
