### ISSUE TITLE
 Alert Silencing - Backend changes

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#36]
We want to add functionality to silence alert for a certain number of hrs. 
User can set silence period i.e. number of hrs that alert notification should not be sent. This can be set on UI and sent to backend using 
`/alerts/silenceAlert` API. This will update the alert table.
- Need to change Alert table definition to include silence_period column.
- Add new API /alerts/silenceAlert 

Alert table has a column, last_sent_time. Every time the alert is triggered , we should check if there is silence_period set for this alert and
has it elapsed i.e. if last_sent_time + silence_period < current_time , then send alert notification. Else alert state is `firing` but no notification is sent since silence_period is not over.

**Comment by Rahhul1309** [comment]
i am gonna work on this

**Comment by venkateshamatam** [comment]
I would like to work on this. I have a few questions - 
1. Where would we like to store this value: in the AlertDetails table or AlertInfo table?
2. Is this expressed in hours or minutes, since the UI ticket for the same functionality indicates it can be passed as number of minutes as well?
3. Do we have an API to fetch these details, since we might need to view the current silence_period in the UI?

**Comment by swethapaturu9** [comment]
I would like to work on this, I have a rough implementation in mind and would like to try my best to add the functionality

**Comment by venkateshamatam** [comment]
Hello @sunitakawane @AndrewHess @nbhavana, I've made the required changes and created a PR https://github.com/siglens/siglens/pull/247. Could you please review it and let me know if any changes need to be made?

**Comment by venkateshamatam** [comment]
Hello @nbhavana, @sunitakawane, @AndrewHess I have implemented this feature and created a PR for your review - https://github.com/siglens/siglens/pull/247. Please let me know if any changes need to be made.

**Comment by nbhavana** [comment]
@venkateshamatam we will review this PR and get back to you asap
