### ISSUE TITLE
[UI] Ability to Delete Index from UI

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#383]
# Description
From the UI, we should have an ability to delete an index.  UI should expose a screen/tab in org-settings to pick an index name from a drop-down and have the delete button. 
This issue id dependent on https://github.com/siglens/siglens/issues/432. 
The UI part can be done, but the integration can be done only when 432 issue is implemented.

# Benefits
Gives flexibility to the user to keep the indices they want.

**Comment by PratikshaPatil77** [comment]
I would like to work on this issue.

**Comment by PratikshaPatil77** [comment]
Would you kindly provide additional information for this issue?

**Comment by nbhavana** [comment]
So for this issue , you need to add a table in org settings tab. The table should display all the available indices and delete icon next to it. The table can look like the table we have for listing dashboards.
If the user clicks the delete icon next to the index, a pop up should come. This pop up will have a OK/Cancel, and the user has to type in the index name again inside the text field in the pop up and once the typed in value matches with the selected delete index icon only then the OK button should be clickable.
<img width="673" alt="image" src="https://github.com/siglens/siglens/assets/6307537/8662c53b-f53c-4d8e-b5c3-a81f71ba8885">

**Comment by Sathish-Kumar-E** [comment]
I want to work on this

**Comment by nkunal** [comment]
go ahead

**Comment by sonamgupta21** [comment]
Resolved with https://github.com/siglens/siglens/pull/943
