### ISSUE TITLE
[UI]  Add thousands separator in the tracing service health table

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#396]
# Description
In the `Tracing` section, in the `service health` tab, we need to add thousands comma seprator

<img width="790" alt="image" src="https://github.com/siglens/siglens/assets/604069/aecb52c0-46f8-4263-a6d6-5431e757a4f3">

# (Optional) Testing
Describe how this should be tested and/or which files unit tests should be added to.

For documentation changes or other similar scenarios, this section can be deleted.

# Acceptance Criteria
List the concrete items that should be completed for this task to be considered completed. Be as clear and thorough as you can.

**Comment by vrajjbhatt** [comment]
Can I work upon this issue?

**Comment by nbhavana** [comment]
yes go ahead
