### ISSUE TITLE
[UI] Make frontend changes for markinga dashboard as a favorite

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#407]
# Description
Currently we have a star icon to mark the dashboard as a favorite, but that marking is not getting saved. 
If the user marks the dashboard favorite, then you need to update the dashboardDetails with this info by calling the `/dashboards/update` endpoint.
 Also, if the user have any dashboards marked as favorite they should listed at the top of the list.

**Comment by PratikshaPatil77** [comment]
I want to work on this.
