### ISSUE TITLE
[UI] The info icon on search text does not display correct queries for Splunk QL and Log QL

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#409]
# Description
 The info icon on search text does not display correct queries for Splunk QL and Log QL. They sample queries in info icon are swictched.

# Steps to Reproduce
1. Click on search text.
2. Now choose Splunk QL in dropdown.
3. Click info icon, you will see sample log queries and not splunk sample queries.
4. Now choose Log QL in dropdown.
5. Click info icon, you will see sample splunk queries and not log sample queries.

Expected Behavior:
When clicked on info icon, the correct sample queries for should be displayed for each type.

<img width="685" alt="image" src="https://github.com/siglens/siglens/assets/6307537/0256963c-60b4-4478-b18b-43529b42c94a">
<img width="422" alt="image" src="https://github.com/siglens/siglens/assets/6307537/3b0c7fd3-2c8e-405e-bc4c-b2c67d0b88bb">

**Comment by PratikshaPatil77** [comment]
I would like to work on this issue.

**Comment by nbhavana** [comment]
This is not a bug, closing this issue.
