### ISSUE TITLE
install_with_git.sh script

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#41]
Create a installation script in bash. It should do the following steps:

1. Check if git is installed (if not prompt the user to install git locally and have them create a GitHub account, point to this link to help them out: https://docs.github.com/en/get-started/onboarding/getting-started-with-your-github-account)
2. then `mkdir siglens-contrib`
3. then `cd siglens-contrib`
4. Then perform `git clone git@github.com:siglens/siglens.git`
5. then `cd siglens`
6. then `go mod tidy` 
8. Check if the current user is allowed to open. port 80 (google how to do this)
9. If yes then do `go run cmd/siglens/main.go -config server.yaml`
10. if not then do `PORT=8090 go run cmd/siglens/main.go -config server.yaml`
11. Display a msg that SigLens is running on port http://localhost:80 or port http://localhost:8090 depending on above 2 steps

Before you execute each step, providing feedback on the terminal saying what you are going to do next. for e.g: "Checking if git exists", "Creating local dirs and cloning git repo", "Downloading go dependencies", "Checking if port 80 is allowed", "Now runing server on port xx", etc...

**Comment by anhlee66** [comment]
I can take this issue.

**Comment by nkunal** [comment]
Thats great ! Thanks

**Comment by sp6370** [comment]
@anhlee66 Are you still working on this?
