### ISSUE TITLE
[BUG] Partial Display of Traces in Search Traces Screen

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#414]
# Description
Even though 100+ traces were sent, only 50 are showing up in the Search Traces screen.

# Steps to Reproduce
Send 100+ traces to the system.
Navigate to the Search Traces screen.

# Expected Behavior
The Search Traces screen should display all sent traces.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by PratikshaPatil77** [comment]
I would like to work on this issue.

**Comment by nbhavana** [comment]
sure go ahead

**Comment by AndrewHess** [comment]
Fixed by https://github.com/siglens/siglens/pull/462
