### ISSUE TITLE
[UI] Remove Replace/Append functionality from Logs Screen.

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#415]
Remove the  point, click, search functionality from the Logs screen 
<img width="1281" alt="image" src="https://github.com/siglens/siglens/assets/71771131/da9d5b10-a5cf-41b5-a1ad-74de96fa1bd1">

**Comment by sanchitd9** [comment]
I want to work on this.

**Comment by sonamgupta21** [comment]
> I want to work on this.

Please go ahead.
