### ISSUE TITLE
[UI] When a trace is selected by mouse, and on click, we should show some details about it for easy debugging.

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#418]
# Description
On tracing page when the user clicks on the graph and select a trace by clicking it, we show some details about the trace.

<img width="874" alt="image" src="https://github.com/siglens/siglens/assets/6307537/8e18a16c-1782-4883-a894-70cc889e1801">

**Comment by PratikshaPatil77** [comment]
I would like to work on this issue.
