### ISSUE TITLE
[NEW] Support podman engine for installation method

### ISSUE THREAD

**Issue by chinmaykhare** [siglens/siglens#437]
# Description
Supporting Podman engine for installation

# Benefits
As Fedora based distributions comes pre-installed with podman, it would be easier for the developers on these platforms to install SigLens. Also Podman and Podman desktop project is now gaining a lot of traction these days as a good open source alternative to Docker Desktop

# (Optional) Possible Implementation
If you have any ideas on how this should be implemented, let us know here.

# (Optional) Additional Context
Currently on Fedora 39 and getting below error if I use the docker install method - 
```

➜  curl -L https://siglens.com/install.sh | sh                                                                                                 (current-context is not set)

----------Setting up docker----------
sudo: apt-get: command not found
sudo: apt-get: command not found
sudo: apt-key: command not found
curl: (22) The requested URL returned error: 404
main: line 143: lsb_release: command not found
sudo: add-apt-repository: command not found
sudo: apt-get: command not found
Installing docker
sudo: apt-get: command not found
{
  "success": false,
  "message": "malformed JSON",
  "code": "invalid_request"
}install_docker: Docker installation failed during apt-get install on linux
```

**Comment by nkunal** [comment]
@Macbeth98 can you pick this up. Thanks
