### ISSUE TITLE
[BUG] Dashboard panel invalid chart type

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#440]
# Description
When you select a Data Source and write the query and click Run Query without choosing a Chart Type, there's a message `Please select a suitable chart type.` which is nice, but if you choose an invalid chart type for the query for some charts it gives no error but doesn't display anything and other times it says `Your query returned no data, adjust your query.` (this was with the Splunk query city=Boston )

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. Make a dashboard and a panel in the dashboard
2. Edit the panel
3. Use the Splunk query `city=Boston`
4. Select various options for the chart and click `Run Query`

# Expected Behavior
When there is no chart selected or an invalid chart for the type of query, it should display the message `Please select a suitable chart type.`

# Environment
- Commit Hash: eabb398

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by PratikshaPatil77** [comment]
I would like to work on this issue.

**Comment by sunitakawane** [comment]
yes, please go ahead.
