### ISSUE TITLE
[BUG] Dashboard add panel workflow

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#443]
# Description
When you add a dashboard panel, it should take you to the page to edit that panel

# Steps to Reproduce
1. Make a dashboard
2. In the top right, click the `+ Add Panel` button

# Expected Behavior
Currently this adds the panel but then you have to click the panel and click Edit to start editing it. Instead, once you click the `+ Add Panel` button, it should make the panel and immediately take you to the page where you edit that panel

# Environment
- Commit Hash: eabb398

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by PratikshaPatil77** [comment]
I would like to work on this issue.

**Comment by AndrewHess** [comment]
Great, go ahead
