### ISSUE TITLE
[BUG] Dashboard panel exit without saving alert

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#444]
# Description
When you edit a panel and click the back arrow, your changes to the panel are discarded and there's no message indicating that.

# Steps to Reproduce
1. Make a dashboard and add a panel
2. Make some changes to the panel (select a Data Source, enter a query, etc.) but don't click the `Save` or `Apply` buttons.
3. In the top left, click the back arrow next to `<MyDashboard> / <MyPanel>` (not the browser's back button)

Observe that your changes to the panel were not saved. You can also edit the panel again and see that your changes were not saved.

# Expected Behavior
When the user clicks that back arrow and there's unsaved changes, a message should pop up asking if the changes should be saved or discarded. When the user clicks the back arrow and there's no unsaved changes, no message should pop up.

# Environment
- Commit Hash: eabb398

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by vibimvab** [comment]
Hi! Can I work on this issue?

**Comment by sunitakawane** [comment]
yes, please go ahead
