### ISSUE TITLE
[BUG] Dashboard panel resizing browser window

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#446]
# Description
When editing a panel with a Pie Chart or Bar Chart, if you resize the browser window the chart disappears. 

# Steps to Reproduce
1. Make a dashboard and make a panel
2. Edit the panel so it does a Log search with Splunk QL for `* | stats count by weekday`
3. Select Pie Chart
4. Click Run Query; you should see a pie chart appear.
5. Now resize your browser window (horizontally or vertically); observe that the chart disappears

# Expected Behavior
The chart should not disappear. If necessary, it can get redrawn.

# Environment
- Commit Hash: eabb398

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by PratikshaPatil77** [comment]
I want to work on this issue.

**Comment by nbhavana** [comment]
Go ahead

**Comment by sonamgupta21** [comment]
Closing issue as the it got fixed with PR https://github.com/siglens/siglens/pull/592
