### ISSUE TITLE
create install_with_binary.sh script

### ISSUE THREAD

**Issue by nkunal** [siglens/siglens#45]
Create a installation script in bash. It should do the following steps:

1. Detect the current OS and set the var OS to: ("linux" for linux and "darwin" for mac) 
2. Detect the arch type and set the arch to: (arm64 OR amd64)
3. Download the "latest_version" file from https://github.com/siglens/siglens/blob/main/pkg/config/version.go  This file will contain the version number of the latest release
4. Construct the download url : <TBD-$latest_verion.$OS.$arch>
5. Download the above url
6. tar -xvf above url file name
7. cd above url file name without the gz
8.  ` PORT=80 ./siglens --config server.yaml`
9. Display a msg that SigLens is running on port [http://localhost:80](http://localhost/) 
10. If above port 80 is not accessible then ask the user to run `PORT=8090 ./siglens --config server.yaml`
11. Before you execute each step, providing feedback on the terminal saying what you are going to do next.

**Comment by sai-vivekanand** [comment]
@nkunal , can I try to solve this as my issue?

**Comment by nkunal** [comment]
I think @sunitakawane has this one assigned to her and its almost complete (will know after she comes back after Diwali holidays)

**Comment by sunitakawane** [comment]
I am working on this and will create a PR for this today.
Thanks
~Sunita
