### ISSUE TITLE
Consider adding an RSS feed to the blog

### ISSUE THREAD

**Issue by marco-m** [siglens/siglens#465]
Hello,
apologies if this is not the right place to ask; I could not find another.

I would like to ask to consider adding an RSS feed to https://www.siglens.com/blog/allblogs.html, so that people can follow new posts using their news readers, instead of subscribing to the mailing list.

thanks!

**Comment by nkunal** [comment]
Thanks for the suggestion, yes we will add it

**Comment by sonamgupta21** [comment]
Hello @marco-m, 
Thank you for your suggestion! We have added RSS feed to our blogs. You can follow new posts using this link: https://www.siglens.com/blog/blog-rss.xml

**Comment by marco-m** [comment]
Thanks @sonamgupta21 :-)
