### ISSUE TITLE
[BUG] Blank panel when no Data Source is selected

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#467]
# Description
When you make a new panel and edit it to run a certain query, but don't select the Data Source, there's no indication that you need to select a Data Source, the panel just silently fails to show anything. We should use the Logs option by default.

# Steps to Reproduce
1. Make a new dashboard and panel
2. Edit the panel and add a query and chart type, but don't select a data source
3. Click the Run Query button or the Apply button, and observe that the panel silently fails.

# Expected Behavior
The Data Source dropdown should have Logs selected by default for new panels. So when you make a new panel and edit it, the dropdown will show Logs instead of Data Source

# Environment
- Commit Hash: 512a448

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by PratikshaPatil77** [comment]
I would like to work on this issue.
