### ISSUE TITLE
`SELECT 1` does not work

### ISSUE THREAD

**Issue by alexey-milovidov** [siglens/siglens#50]
Playground (http://playground.sigscalr.io/index.html) shows this:

![Screenshot_20231108_021559](https://github.com/siglens/siglens/assets/18581488/3a3b1a3f-ea84-41a7-99d9-43add13c4ccd)

**Comment by alexey-milovidov** [comment]
The gray color of the text has low contrast, which makes it unreadable if you are located on the beach in sunny weather.

**Comment by alexey-milovidov** [comment]
The text has inconsistent punctuation: there is a whitespace after the first colon but not after the second.

**Comment by alexey-milovidov** [comment]
It pronounces SQL in an inconsistent way: first it says "SQL", then "sql".

**Comment by Pranav014** [comment]
I want to work on it

**Comment by AndrewHess** [comment]
Sure, go ahead. Are you going to work on the `SELECT 1` issue or the other things mentioned?

**Comment by venkateshamatam** [comment]
@AndrewHess It looks like select 1 works now without an error, but it always returns 1 row with 1 column and not all the matched rows

**Comment by nkunal** [comment]
It is supposed to return just 1 row but all the columns

**Comment by venkateshamatam** [comment]
I can work on this! Just confirming - SELECT 1 statement specifies returning the constant value 1. So this query will only return a single column - that column will contain the value 1 for each row that satisfies the condition, if there is any condition, right? @nkunal @AndrewHess

**Comment by nkunal** [comment]
It is supposed to return just 1 row but all the columns

**Comment by venkateshamatam** [comment]
Okay sure, so it is essentially the same as doing SELECT * from `*` LIMIT 1 ?
