### ISSUE TITLE
[BUG] install_with_docker.sh failed due to github api rate limit

### ISSUE THREAD

**Issue by lonetrail** [siglens/siglens#524]
# Description
Clearly describe the bug and how to reproduce it. If applicable, include screenshots.

If the GitHub API rate limit exceeds, SIGLEN_VERSION in install_with_docker.sh will be empty, leading to the failure of install_with_docker.sh.
``` sh 
 curl  --silent "https://api.github.com/repos/siglens/siglens/releases/latest"
{"message":"API rate limit exceeded for 38.207.136.179. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```
The installation will fail with error message below:
``` sh
Pulling the latest docker image for SigLens from upstream
invalid reference format
{
  "success": true
}Failed to pull siglens/siglens:. Please check your internet connection and Docker installation.
```

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. run command `curl -L https://siglens.com/install.sh | sh`

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by nbhavana** [comment]
Thank you for submitting the bug, we will get it resolved soon.

**Comment by lonetrail** [comment]
The GitHub API rate limit is 60 requests per hour for the same IP address. Therefore, when using a VPN with shared IPs, this issue may arise. Currently, 60 requests per hour from the same IP address may be considered acceptable?
