### ISSUE TITLE
[STORY] Add unit tests for HasGroupByOrMeasureAggsInChain

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#533]
# Description
`HasGroupByOrMeasureAggsInChain` is defined in segstructs.go. Add thorough unit testing for this function in segstructs_tests.go in the same folder

Note: You need to name your function(s) so they start with `Test_`; that way Go's unit testing procedure will find that function when it looks for test functions

# Acceptance Criteria
* The added unit tests are clear and thoroughly test the function
* Your new unit tests run and pass when you run `make test` or `make pr` from the siglens base directory
* If adding comments to your code makes it easier to understand, you should add them. If the code is already self-explanatory, you can skip them
* Running `make pr` gives no errors

**Comment by xmh1011** [comment]
I'll fix it.

**Comment by AndrewHess** [comment]
Great, go for it
