### ISSUE TITLE
[STORY] Remove duplicate SetBadMsg definitions

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#538]
# Description
The function `SetBadMsg()` is defined almost identically in around 8 different files. Define it in pkg/utils/httpserverutils.go and remove all the other definitions. The definition in querytracker.go is slightly different because it allows customizing the message; since we don't want to change any functionality, you can either define two variations (one with a preset message and one with a custom message) or define just one function such that it uses the default message if no message is provided

# Acceptance Criteria
* All redundant definitions of the function are removed
* There shouldn't be any functional changes to the code, as this is just a refactoring change
* Running `make pr` from the siglens base directory gives no errors

**Comment by Jiale-Fang** [comment]
Can i go for this?
