### ISSUE TITLE
[STORY] Add error handling to parseAlphaNumTime

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#539]
# Description
`parseAlphaNumTime()` is defined in pkg/ast/pipesearch/searchHandler.go. It converts strings like `now-1h` (meaning one hour before now) to a unix timestamp in milliseconds. However, the code is a little messy and doesn't properly handle invalid cases (e.g., strings like `Hello, World!`). You should refactor/comment this code to make it more legible and add error handling.

# Acceptance Criteria
* The new version of the function should be easy to understand and return an error if the input values are invalid.
* Running `make pr` from the siglens base directory gives no errors

**Comment by abhinavg1997** [comment]
I can pick it up

**Comment by abhinavg1997** [comment]
Hey Andrew, I had a question with respect to checking the length of the input value. While having a check for "less than 6 characters" makes sense, should there be an upper bound check? Based off of the possible values, the highest it can currently go would be 7 characters "now-90d" but that could change in the future.
Moreover I see test cases that are checking for 3 digit values which would fail if we keep a 7 character limit. 
Could use your opinion on this

**Comment by AndrewHess** [comment]
You don't need an upper bound on the length; as long as the string is properly formatted, we should handle it. You could have a check to make sure we don't overflow the return value, but since it's a `uint64` and we're returning unix milli time, this shouldn't really ever be an issue unless some of the inputs to the function are very wrong.

Also if you want you can remove/refactor that check for less than 6 characters. That's there because we need at least something like `now-1s` which has 6 characters, but that's not immediately obvious from just quickly looking at the code, so if there's a cleaner way to handle that check that doesn't have a magic number that could help clean up the code

**Comment by gouthamhusky** [comment]
Hey @AndrewHess , does this need to be assigned to me to open a PR or can I go ahead?

**Comment by nkunal** [comment]
You can just go ahead
