### ISSUE TITLE
[STORY] Refactor PipeSearchRequest duplicate code

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#540]
# Description
In pkg/ast/pipesearch/searchHandler.go, the functions `ProcessPipeSearchRequest` and `ProcessAlertsPipeSearchRequest` share a lot of the same code. Refactor this so that the shared code is in a different function that both of these functions call, so that there's a lot less duplicate code.

# Acceptance Criteria
* No functionality should change, this is just a refactoring change.
* There shouldn't be significant code duplication between the two functions 
* Running `make pr` from the siglens base directory gives no errors

**Comment by Jiale-Fang** [comment]
Can i work on this issue?

**Comment by dongrep** [comment]
@AndrewHess  I can see a new function that both functions now use ```ParseAndExecutePipeRequest```. I think that makes this store obsolete?
