### ISSUE TITLE
[BUG] The toggle for Dark/Light Mode is not functioning on the saved queries page.

### ISSUE THREAD

**Issue by venkateshamatam** [siglens/siglens#541]
# Description
The toggle for Dark/Light Mode is not functioning on the saved queries page.

# Steps to Reproduce
1. Go to the saved queries page at `/saved-queries.html`.
2. Try to switch between Dark and Light modes using the toggle located at the bottom left of the page. Observe that the mode does not change.

# Expected Behavior
The Dark/Light Mode switch should function correctly and consistently across all pages.

**Comment by kiko2k3** [comment]
Can I work on this issue?

**Comment by nkunal** [comment]
Yes go ahead please

*Best Regards*
*-- Kunal Nawale ,**Founder/CEO, SigScalr*

**Comment by YBY2000** [comment]
Can i work on this?

**Comment by nbhavana** [comment]
go ahead
