### ISSUE TITLE
[STORY] Centralize the definition of default dashboards IDs

### ISSUE THREAD

**Issue by venkateshamatam** [siglens/siglens#543]
# Description
- We have some default dashboards that are pre-existing and not user-generated. Currently, we are filtering these default dashboards from all dashboards in various parts of the code. To minimize redundancy and potential errors, these default dashboards should be defined once as a constant, and this constant should be utilized throughout the code base.
- You can find the list of default dashboard IDs in `/defaultDBs/allids.json`

# Testing
- Test that no existing functionality is broken.
- Manually test the Dashboard UI and make sure the all the APIs returned by GET `/api/dashboards/defaultlistall` API is shown on the UI.
- Verify that favorite functionality works and maintains its state on refresh for default and non-default dashboards.

**Comment by sonamgupta21** [comment]
Resolved with #1125
