### ISSUE TITLE
UI : Add Clear Button to Reset Query Builder

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#549]
# Description
Add a small "X" icon at the end of the search box in the query builder. 
This icon will work similarly to what we already have in the Free Text tab, allowing users to quickly clear their query and start over.
<img width="1427" alt="image" src="https://github.com/siglens/siglens/assets/71771131/7598dbe0-7425-47ef-b39e-ef8f6f7db0db">

**Comment by miguelteixeira123456789** [comment]
I would like to work on this issue. Could you please assign it to me?
