### ISSUE TITLE
Slower than expected

### ISSUE THREAD

**Issue by alexey-milovidov** [siglens/siglens#55]
A dashboard in the Playground: http://playground.sigscalr.io/dashboard.html?id=ad843ef0-3dc9-4368-806e-a85f2a769179 takes minutes to display charts. Which is unreasonably slow for that small data volume.

![Screenshot_20231108_023916](https://github.com/siglens/siglens/assets/18581488/16897d04-71b0-4a17-aed6-eb6342233b55)

This is only for 44,857,142 records. For comparison, a minimal ClickHouse service in the dev tier will serve it instantly.

**Comment by nkunal** [comment]
This has been fixed in recent release. Also the playground is now running on port 5122
