### ISSUE TITLE
[STORY] UI : Add Correct Titles for Buttons

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#550]
# Description
Review and update the titles for all buttons in the UI to ensure they accurately describe the action or function of each button.

When users hover over any button in the UI, a tooltip with the correct title should appear.
<img width="1418" alt="image" src="https://github.com/siglens/siglens/assets/71771131/00cba5b6-f853-4951-a2d3-c64c9e62634e">

**Comment by mvchaitanya14** [comment]
Can I work on this issue?

**Comment by shahdharmil11** [comment]
I want to work on this issue

**Comment by deodhar-ad** [comment]
i want to work on this

**Comment by nbhavana** [comment]
go ahead
