### ISSUE TITLE
[STORY] UI : Update CSS Style for Save Query Dialog Box

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#551]
# Description
Update the CSS style for the Save Query dialog box to ensure consistency.
Input box and the button height should be - 32px
Heading - "Save Query" - 18px
<img width="1422" alt="image" src="https://github.com/siglens/siglens/assets/71771131/209a73a2-360f-4d6b-8462-a29eb59e1ebe">

# Steps to reproduce
1. On Logs screen, click the "disk" icon to open Save Query dialog box.

**Comment by PratikshaPatil77** [comment]
I want to work on this issue.
