### ISSUE TITLE
[STORY] UI :  Update CSS Style for Delete Popup on Alerting Screens

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#552]
# Description
Update the CSS style for the Delete popup for alerts and contact point.
The input box and the button height should be - 32px
Heading - "Save Query" - 18px
<img width="1271" alt="image" src="https://github.com/siglens/siglens/assets/71771131/402e35a9-6145-443c-9ada-90c56c33d460">
<img width="1265" alt="image" src="https://github.com/siglens/siglens/assets/71771131/f0941500-ea34-4f09-b954-9f404c681c7f">

# Steps to reproduce
1. Create alert and contact point , and then try to delete it.

**Comment by PratikshaPatil77** [comment]
I want to work on this issue.
