### ISSUE TITLE
[STORY] Add Alt Text for Dashboard Panel Chart Icons

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#553]
# Description
In `dashboard.html` add `alt` text for images.
Add descriptive text to describe each icon.

<img width="1430" alt="image" src="https://github.com/siglens/siglens/assets/71771131/07c2daad-95cd-40bf-94ee-12e5530d7b49">

**Comment by AndrewHess** [comment]
> I'd like to work on this. May I know if there are any prerequisites to be completed before starting or while working on the issues ? 🙂

Go for it! There's some information in the [Contributing Guide](https://github.com/siglens/siglens/blob/develop/CONTRIBUTING.md) about setting up your environment for development and our PR workflow
