### ISSUE TITLE
[STORY] UI : Adjust Tooltip Appearance in Scatter Chart for Dark Theme

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#554]
# Description
We need to adjust the appearance of tooltips in the scatter chart on the search trace page to match the dark theme. 

Currently, the tooltips have a white background, which is not consistent with the dark theme used throughout the UI. 
<img width="1257" alt="image" src="https://github.com/siglens/siglens/assets/71771131/0f18484b-ce8c-4dfb-b387-b13c3e7c77ec">

We want to update the tooltip background color to match the dark color scheme used for other tooltips in the UI.
<img width="1391" alt="image" src="https://github.com/siglens/siglens/assets/71771131/42dd86ef-3821-49ad-8b31-198140ad7975">

**Comment by KaushikMreddy** [comment]
I want to work on this

**Comment by nbhavana** [comment]
go ahead

**Comment by KaushikMreddy** [comment]
is this bug still there?

**Comment by nbhavana** [comment]
This issue is fixed
