### ISSUE TITLE
[STORY] Fix CSS Style: Available Fields on Live Tail Screen

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#556]
Fix the style of the `Available Fields` dropdown on the Live Tail Screen and make it similar to the available fields on Logs screen.

<img width="1265" alt="image" src="https://github.com/siglens/siglens/assets/71771131/5e317a8c-fae6-44f9-b6fd-292b713f0edc">

**Comment by saniya16** [comment]
I would like to work on this issue

**Comment by nbhavana** [comment]
go ahead
