### ISSUE TITLE
[STORY] UI : Disable Search Query Button for Incorrect Queries

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#558]
# Description
Disable the search query button when the query built through the query builder is incorrect. 
Currently, we grey out the button, but it remains clickable. We should disable the button, preventing users from clicking it when the query is incorrect.

<img width="1269" alt="image" src="https://github.com/siglens/siglens/assets/71771131/a205397e-f476-458c-bd75-6fbccf6fac35">

**Comment by El-Psy-Kongrooo** [comment]
I would like to be assigned to this issue, i think i can fix this

**Comment by nkunal** [comment]
Yea please go ahead

**Comment by Malini240** [comment]
I would like to be assigned to this

**Comment by nbhavana** [comment]
go ahead

**Comment by El-Psy-Kongrooo** [comment]
"Hey @nbhavana, just a heads up, I've submitted a pull request and completed the issue. Now, I'm patiently awaiting feedback. Thanks for your time!"

**Comment by nbhavana** [comment]
> Hey @nbhavana, just a heads up, I've submitted a pull request and completed the issue. Now, I'm patiently awaiting feedback. Thanks for your time!

@El-Psy-Kongrooo sorry it took long  to review the PR.  I just reviewed the PR.
