### ISSUE TITLE
[STORY] Add Unit Tests for Stats Aggregation function Following Rex Columns

### ISSUE THREAD

**Issue by Macbeth98** [siglens/siglens#560]
# Description
- `PerformMeasureAggsOnRecs`  is a function that aggregates data with the given Measure Aggregations.
- Another function, `PerformAggsOnRecs`, invokes this aggregation function. When constructing your test case, ensure it calls `PerformAggsOnRecs` and inputs data in a manner that guarantees the primary function `PerformMeasureAggsOnRecs` is always executed. 
- You can achieve this by setting `nodeResult.PerformAggsOnRecs: true` and `nodeResult.RecsAggsType=structs.MeasureAggsType`.
- This function is defined in the `searchaggs.go` file.
- Write Unit Tests for this method in a file called `searchaggs_test.go`. If the file does not exist create the file in the same folder.

**Note**: You need to name your function(s) so they start with `Test_`; that way Go's unit testing procedure will find that function when it looks for test functions 

**References:**
- You can take the reference of this test case `Test_processTransactionsOnRecords` defined in the `segaggs_test.go` file to build your test cases. 
- It's not necessary to replicate the structure, style, or quantity of examples from this test case exactly; it's provided merely for inspiration.

# Acceptance Criteria
- The added unit tests are clear and thoroughly test the function
- Your new unit tests run and pass when you run `make test` or `make pr` from the siglens base directory
- If adding comments to your code makes it easier to understand, you should add them. If the code is already self-explanatory, you can skip them
- Running `make pr` gives no errors

**Comment by dongrep** [comment]
@Macbeth98 @AndrewHess Could you confirm if this is already implemented, I could see that there exists serachaggs_test.go exists and It has multiple tests invoking PerformAggsOnRecs function.
And this is what we wanted to test is what I understood from the description.

**Comment by AndrewHess** [comment]
I believe this issue is specifically for after a `rex` command. Can you confirm @Macbeth98 ? If that's the case, I don't think the unit test has been added already

**Comment by Macbeth98** [comment]
@AndrewHess This is not specifically after a `rex` command. But that is one of the flows which will go through this part of the code. 
And also yes the tests have already been written. So I think we can close this issue @AndrewHess .
