### ISSUE TITLE
[STORY] Add unit test for PerformArithmeticOperation

### ISSUE THREAD

**Issue by Macbeth98** [siglens/siglens#561]
# Description
- `performArithmeticOperation` function is defined in `segaggs.go`. Add thorough unit testing for this function in `segaggs_test.go` in the same folder

**Note**: You need to name your function(s) so they start with `Test_`; that way Go's unit testing procedure will find that function when it looks for test functions

# Acceptance Criteria
- The added unit tests are clear and thoroughly test the function
- Your new unit tests run and pass when you run `make test` or `make pr` from the siglens base directory
- If adding comments to your code makes it easier to understand, you should add them. If the code is already self-explanatory, you can skip them
- Running `make pr` gives no errors

**Comment by mvchaitanya14** [comment]
Can i work on this issue?

**Comment by nbhavana** [comment]
go ahead

**Comment by xmh1011** [comment]
I have provided a new unit test for `performArithmeticOperation`, plz check. Thank you. @nbhavana @Macbeth98 @AndrewHess
