### ISSUE TITLE
[STORY] Add unit test for the GetOrCreateNodeRes

### ISSUE THREAD

**Issue by Macbeth98** [siglens/siglens#562]
# Description
- `GetOrCreateNodeRes` is defined in `rrcreader.go`. Add thorough unit testing for this function in `rrcreader_test.go` in the same folder.
- Write tests to verify that the function correctly retrieves an existing `NodeResult` instance for a given `qid`.
- Write tests to ensure that if no existing `NodeResult` matches the `qid`, a new instance is created, added to the global map, and returned.

**Note**: You need to name your function(s) so they start with `Test_`; that way Go's unit testing procedure will find that function when it looks for test functions

# Acceptance Criteria
- The added unit tests are clear and thoroughly test the function
- Your new unit tests run and pass when you run `make test` or `make pr` from the siglens base directory
- If adding comments to your code makes it easier to understand, you should add them. If the code is already self-explanatory, you can skip them
- Running `make pr` gives no errors

**Comment by HemantGaikwad7** [comment]
I want to work on it

**Comment by nbhavana** [comment]
go ahead

**Comment by ahegde3** [comment]
Can I work on this ?

**Comment by nkunal** [comment]
yes go ahead
