### ISSUE TITLE
[STORY] UI : JSON Box should be smaller or fit in the box

### ISSUE THREAD

**Issue by navyayy** [siglens/siglens#572]
# Description
![image](https://github.com/siglens/siglens/assets/108896805/d782ef0b-bc85-4a67-b45a-10ae9e107d4c)

Here, the JSON box is too large that the contents are not visible, it should be smaller in size such that it should fit in the box.

**Comment by mematcha** [comment]
Can I work on this?

**Comment by nbhavana** [comment]
go ahead

**Comment by Spoorthikulkarni01** [comment]
Can I work on this?

**Comment by nbhavana** [comment]
> Can I work on this?

its already assigned to someone else

**Comment by kaushikMreddy293** [comment]
If this has not been completed, can I work on this?

**Comment by nbhavana** [comment]
The issue is still open. You can submit a PR  if you are interested.
