### ISSUE TITLE
[STORY] UI : The text and icon are getting clashed at the end of the search bar

### ISSUE THREAD

**Issue by navyayy** [siglens/siglens#573]
# Description
![image](https://github.com/siglens/siglens/assets/108896805/76a83a8f-21b7-4922-aae8-257566aa7d7b)

Here, the text is getting below the icon, the text should only come till before the icon

**Comment by Ramalhadas** [comment]
Can i work on this issue?

**Comment by nkunal** [comment]
Yes go ahead

*Best Regards*
*-- Kunal Nawale ,**Founder/CEO, SigScalr*

**Comment by Ramalhadas** [comment]
I've resolved this issue. Additionally, I've implemented a "Clear" button (denoted by an "X") positioned to the right of the text field and to the left of the Information Icon. This feature aligns with existing implementations across other areas of SigLens. While I believe this consistency supports the change, I'd appreciate any feedback or confirmation on this addition to ensure it meets the project standards and expectations.

**Comment by yugallakhyani11** [comment]
Hi, I want to work on this.

**Comment by nbhavana** [comment]
go ahead

**Comment by laughtale678** [comment]
Can I work on this?

**Comment by KaushikMreddy** [comment]
I want to work on this. 
I have fixed the issue, would like to raise a PR as well.

**Comment by nbhavana** [comment]
> I want to work on this. I have fixed the issue, would like to raise a PR as well.
> 
> ![image](https://private-user-images.githubusercontent.com/144624017/317146188-d3b709c8-f3d3-46ea-bac1-780d819fee78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzkwNDIsIm5iZiI6MTcxMTUzODc0MiwicGF0aCI6Ii8xNDQ2MjQwMTcvMzE3MTQ2MTg4LWQzYjcwOWM4LWYzZDMtNDZlYS1iYWMxLTc4MGQ4MTlmZWU3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMTI1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODUyYmEwOTViODhkZTQwMjJhODRkN2IxNDI4MTMzZjc3ZDlmNzgyNGE1YmM5MzdlZDUwYzBlMWJlOTQ1MWIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zKrq6aoO9eJyGavNA0y2_wM4rJ5KG6dH0xf5YKuRkQA)

sure, you can submit a PR

**Comment by Ramalhadas** [comment]
@nbhavana i have already solved this issue, as you can see from the comments above and will send the PR soon. Can you please tell me what you think about the clear button i mentioned above and accept my PR if its acceptable?

**Comment by nbhavana** [comment]
> @nbhavana i have already solved this issue, as you can see from the comments above and will send the PR soon. Can you please tell me what you think about the clear button i mentioned above and accept my PR if its acceptable?

@Ramalhadas can you submit a PR so we can take a look at the implementation you are talking about?

**Comment by Ramalhadas** [comment]
> > @nbhavana i have already solved this issue, as you can see from the comments above and will send the PR soon. Can you please tell me what you think about the clear button i mentioned above and accept my PR if its acceptable?
> 
> @Ramalhadas can you submit a PR so we can take a look at the implementation you are talking about?

Yes i will send it. Thank you for your response and please wait for my PR.

**Comment by Ramalhadas** [comment]
@nbhavana Thank you for waiting. I Hope everything is fine.
