### ISSUE TITLE
[BUG] Disable the functionality to edit the default dashboard details

### ISSUE THREAD

**Issue by venkateshamatam** [siglens/siglens#576]
# Description
Since the details of default dashboards cannot be modified, we should deactivate this feature in the user interface.

# Steps to Reproduce
1. Go to any of the default dashboard page page  `/dashboard.html?id=a28f485c-4747-4024-bb6b-d230f101f852` and click on the gear icon on top right to edit the dashboard details.
2. Disable the functionality to edit the dashboard details since they are not editable with a small message/indication to the user that these details cannot be edited.

# Expected Behavior
- The ability to edit should be disabled only for default dashboards, without affecting the functionality of non-default dashboards.
- Rely on the API response to determine if these dashboards are editable. This approach simplifies the process of controlling which dashboards can be edited, as it only requires changes to the server code.

**Comment by KiritoCyanPine** [comment]
Hi , I'd like to work on this issue.

**Comment by AndrewHess** [comment]
Great, go ahead

**Comment by KiritoCyanPine** [comment]
Hi @AndrewHess @venkateshamatam  , I think the current `api/dashboards/{dbID}` API dosent give enough information to determine if the dashboard is a default one. 

The properties returned are -> `name`, `description`, `panels`, and `timeRange`. 
I think the absence of the properties like `isFavorite` and `refresh` could determine if the dashboard is a default one. But in longer run it may not be that effective for a solution. 

Should it be fine to create a new api to determine default dashboards ? something like `api/dashboards/isdefault/{dbID}` .

**Comment by AndrewHess** [comment]
Yes you can add that endpoint. Alternatively, you should be able to call `api/dashboards/defaultlistall` to get the IDs of all the default dashboards and check if the current dashboard's ID is in that list

**Comment by Sneha393** [comment]
I want to work on it

**Comment by nbhavana** [comment]
go ahead

**Comment by KiritoCyanPine** [comment]
Is the above issue resolved ?

**Comment by AndrewHess** [comment]
@sonamgupta21 can you review https://github.com/siglens/siglens/pull/601 to fix this issue?
