### ISSUE TITLE
UI- Add timechart as chart type

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#595]
# Description
UI- Under dashboards , if we have selected SPL as query language, for timechart queries we should add timechart as chart type 

# Benefits
Describe why you want this feature.

# (Optional) Possible Implementation
If you have any ideas on how this should be implemented, let us know here.

# (Optional) Additional Context
Add anything else we should know about this.

**Comment by divyakasa09** [comment]
I want to work on this.

**Comment by nbhavana** [comment]
sure, go ahead
