### ISSUE TITLE
[STORY] Doc : Add macOS setup instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by SuperAayush** [siglens/siglens#628]
In the current CONTRIBUTING.md file there is a mention of running `build-essential` commands to setup Siglens for Linux which might confuse users of other OS. 

For example the below line:
https://github.com/siglens/siglens/blob/f300f2ea4f3df41c1bdd4d04069407cf64ae9277/CONTRIBUTING.md?plain=1#L83

Can be reframed as this:
**...Otherwise, please execute the following commands(ignore running below commands if you are setting up locally on macOS, directly jump to the Start up Siglens section)**

Or to make it more contributor friendly we can change the line to:

**Siglens currently support Linux and macOS for development purposes.** 
- **To setup project locally on `macOS` please jump to Start up Siglens(link) section.**
- **For Linux systems, the `build-essential` package is necessary. If it's already installed, no action is needed. Otherwise, please execute the following commands**

I did also see that the current CONTRIBUTING.md does not have any instructions on creating issues, adding that will help in categorizing issue creation.

cc - @nkunal

**Comment by SuperAayush** [comment]
Can go with a PR with either of the suggested changes, please drop your thoughts

**Comment by nbhavana** [comment]
yes, go ahead
