### ISSUE TITLE
[STORY] : add new issue type -- `DOC`

### ISSUE THREAD

**Issue by SuperAayush** [siglens/siglens#659]
#### Main issue:
Currently, there is no issue type available to target document-related issues, I think there should be one more Issue Type named Doc to target documentation changes.

#### Sub issue:
The golinter link in the CONTRIBUTING.md is not working:
https://github.com/siglens/siglens/blob/a73152da87724525e9d23b92b924756a45d08b72/CONTRIBUTING.md?plain=1#L81

cc - @nbhavana

**Comment by AndrewHess** [comment]
Good idea. I made this PR #666 to add a Documentation issue template
