### ISSUE TITLE
SQL: Add Round

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#67]
We want to support using `ROUND` in SQL queries as described here: https://www.postgresqltutorial.com/postgresql-math-functions/postgresql-round/

We do SQL parsing in `pkg/ast/sql/astsql.go` but you may also need to look into `github.com/xwb1989/sqlparser` as we use that to do some of the parsing. You may also want to look at how we implemented `round()` for Splunk QL by parsing it in `pkg/ast/spl/spl.peg` and evaluating it in `pkg/segment/structs/evaluationstructs.go`, which we call in `pkg/segment/aggregations/segaggs.go`

**Comment by Macbeth98** [comment]
I want to work on it.

**Comment by nkunal** [comment]
Fantastic! Please go ahead
