### ISSUE TITLE
[BUG]  - Get Contacts is throwing 400 Bad Request when 

### ISSUE THREAD

**Issue by Amith-CS** [siglens/siglens#677]
# Description
Unable to Save a Contact point when Type is selected as Webhook, and providing a webhook url

# Steps to Reproduce
1. Go to the Alerting section
2. Navigate to 'Contact Point' sub-tab
3. Click on 'Add Contact Point'
4. Provide a Contact Point name
5. Select the 'webhook' type
6. Provide a webhook url and try to save

# Expected Behavior
Contact point should save without any errors.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by sujeshthekkepatt** [comment]
I think this due to `webhook` is of type `[]string` and sqllite doesn't support arrays. So during scan it fails. 
```WARN[0032] SELECT * FROM `contacts` WHERE org_id = 0     component=gorm duration=0.294625 error="sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string; sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string; sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string; sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string" rows=4
WARN[0577] SELECT * FROM `contacts` WHERE org_id = 0     component=gorm duration=1.0725 error="sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string; sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string; sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string; sql: Scan error on column index 4, name \"webhook\": unsupported Scan, storing driver.Value type string into type *[]string" rows=4```
