### ISSUE TITLE
 [STORY] SPL Add sub command list 

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#746]
# Description
Implement the sub command `list` under the `stats` SPL command
reference:https://docs.splunk.com/Documentation/SplunkCloud/9.1.2312/SearchReference/Multivaluefunctions

# (Optional) Additional Context
sample query:
`search index=*-wfd-dmq-app host=*** sourcetype=rabbitmq (mnesia_down) OR (*partition*) | stats list(_raw) by host _time`

**Comment by saniya16** [comment]
I would like to work on this

**Comment by nkunal** [comment]
Go ahead

**Comment by deodhar-ad** [comment]
Hi, I would like to work on this.

**Comment by nkunal** [comment]
Go ahead

**Comment by Shiva-017** [comment]
Hi, I want proceed with it

**Comment by sathkrith** [comment]
I would like to work on this.

**Comment by smitneu3009** [comment]
I would like to work on this

**Comment by ankush98m** [comment]
I'll be working on it

**Comment by light9988** [comment]
I will be working on it
