### ISSUE TITLE
[STORY] SPL: Add mvindex

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#747]
# Description
Add the sub command `mvindex` under `eval` command for SPL

reference: https://docs.splunk.com/Documentation/SplunkCloud/9.1.2312/SearchReference/MultivalueEvalFunctions#mvindex.28.26lt.3Bmv.26gt.3B.2C.26lt.3Bstart.26gt.3B.2C.26lt.3Bend.26gt.3B.29

Sample query:
`'search index=\"*wfd-wfm-app\" host=*** sourcetype=\"wfm:healthcheck:monitoringapi\" host=*prd50** \"Notifications Sent in last*\" | rex field=msg \"^.*{(?<metrics>.*)}\" | table _time host metrics | eval m = mvindex(split(metrics, \",\"),0) |eval tmp=split(metrics,\",\") |mvexpand tmp |rex field=tmp \"(?<key>[^=]*)\\=(?<value>[^$]*)\" |table _time host key value | where NOT LIKE(key,\"%TOTAL%\") |timechart span=10m sum(value) by key useother=f limit=0'`

**Comment by saniya16** [comment]
Hi, I want to work on it

**Comment by girish332** [comment]
I'll be working on this

**Comment by Shiva-017** [comment]
May I proceed to work on this?
