### ISSUE TITLE
[STORY] SPL: Add append

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#749]
# Description
Add `append` command

reference:https://docs.splunk.com/Documentation/Splunk/9.2.1/SearchReference/Append

Sample Query:
`search index=*infra* sourcetype=infra_cpu host=cust01-**dmq*\n| eval cpuutil=pctUser+pctSystem\n| timechart span=15m max(cpuutil) as CPUUtil\n|append [ search index=*infra* sourcetype=infra_memory host=cust01-prd0**dmq* | eval MemUsedPercentofTotal = round((used*100)/total,2)\n| eval MemFreePercentofTotal = round((free*100)/total,2)\n| eval MemBufferCachePercentofTotal = round((buff_cache*100)/total,2)\n| timechart span=15m max(MemUsedPercentofTotal) as MaxMem ]\n| append [ search index=koogle-monitoring source=messaging-metrics-details data_type=queues publish!=null host=cust01-prd0**dmq* |eval que_vhost=queue_name+\"@\"+vhost+hostname | sort 0 _time | streamstats current=false last(publish) as last_publish by que_vhost\n| eval publish_rate_of_change = if(publish>last_publish, round((publish - last_publish)/900,2), 0)\n| timechart span=15m sum(publish_rate_of_change) as publish_rate_persec ]\n| append\n[search index=*koogle-monitoring* source=\"messaging-metrics-details\" data_type=queues queue_name!=\"aliveness-test\" AND queue_name!=\"dead-letter-Queue\" host=cust01-prd0**dmq*\n| timechart span=15m sum(messages) as queued_messages ]`

**Comment by deogadepallavi** [comment]
Hello Team,
Can I work on this issue?
Thanks

**Comment by AndrewHess** [comment]
Yep!

**Comment by basupatil1213** [comment]
I will be working on it

**Comment by suchitadabir** [comment]
Hi, can I work on this?

**Comment by AndrewHess** [comment]
Yes you can work on it. I think this is going to be a rather complicated change, but feel free to work on it

**Comment by suchitadabir** [comment]
Sure, thank you! 
I'll start working on it.

**Comment by ankush98m** [comment]
I'll be working on it.

**Comment by smitneu3009** [comment]
I'll start working on it.

**Comment by light9988** [comment]
I will be working on it

**Comment by mrunalipawar97** [comment]
I will be working on it
