### ISSUE TITLE
[STORY] SPL: Add bin

### ISSUE THREAD

**Issue by nbhavana** [siglens/siglens#751]
# Description
Add `bin` command

reference:https://docs.splunk.com/Documentation/SplunkCloud/9.1.2312/SearchReference/Bin

Sample query:
`"'\n| search (index=*infra* OR index=*kcap*) sourcetype=infra_process\n[| gentimes start=-1 | eval host=\"koss01-oss01-prx18-app*,koss01-oss01-ins01-orc02-app*,koss01-oss01-mta18-app*\" | makemv delim=\",\" host | mvexpand host | table host | format]\n| table _time host command args\n| bin span=5m _time\n| stats count by host _time command args\n| eval cmd = command . \"|\" . args . \"|\" . count\n| stats values(cmd) as cmds by _time host\n| eval splunkd_count = mvindex(split(mvindex(cmds, mvfind(cmds, \"splunkd\")), \"|\"), 2)\n| table _time host splunkd_count cmds\n| eval cmds = mvjoin(cmds, \"|||\")\n| stats latest(cmds) as cmds by host\n| eval cmds = split(cmds, \"|||\")\n| rex field=host \"^(?<host>.*?)\\..*$\"`

**Comment by deogadepallavi** [comment]
Hello Team, 
Can I work on this issue?
Thanks

**Comment by AndrewHess** [comment]
Sure, go ahead!

**Comment by suchitadabir** [comment]
I will be working on it

**Comment by AndrewHess** [comment]
Hey sorry I forgot to close this issue. We've actually already implemented `bin` in #1216 and #1246
