### ISSUE TITLE
[STORY] Display error spans in Gantt chart

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#790]
# Description
Note: #789 needs to be merged first

The tracing UI shows how many spans had an error
![image](https://github.com/siglens/siglens/assets/20426590/5821631d-8879-4566-b908-fb53ff12519c)
But when you click that trace to go to the Gantt chart, it's not easy to see which spans had an error.

Once #789 is merged, the frontend will have the `Status` field for each span in the chart. Use this field to color error spans a distinct color (maybe red).

# Acceptance Criteria
If you click on a trace with some error spans, those error spans are a different color than the rest of the spans, so they are easy to identify.

**Comment by sonamgupta21** [comment]
Resolved with https://github.com/siglens/siglens/pull/821
