### ISSUE TITLE
Tracing : Dependency Graph

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#82]
When the user clicks on the tracing icon in the side navbar and navigates to the "Dependency Graph" tab, display the overall call paths of the spans.

Call an API (api/traces/dependencies) to get the matrix of service path counts, and then create a force-directed graph using a library like D3.js.
Root nodes should be positioned at the top of the graph.

```
endpoint: api/traces/dependencies
method: GET
Example:
request: http://localhost:80/api/traces/dependencies
response: 
    {[
		{
			"from": string (parent service),
			"to": []int (N elements, where N is the number of services. Each value is the number of calls from "from" to "to"
		},
		...
    ]}
```
Similar to below image -
![image](https://github.com/siglens/siglens/assets/71771131/e7c2f92a-fc84-452a-ad86-48d2ede0ab41)

**Comment by AndrewHess** [comment]
The backend for the dependency graph was implemented in https://github.com/siglens/siglens/pull/71 and the API response changed a little. So now the response will be something like:
```
{
    "ServiceA": {
        "ServiceB": 5,
        "ServiceC": 2
    },
    "ServiceB": {
        "ServiceC": 4
    }
}
```
