### ISSUE TITLE
UI: Display an empty drop-down when do "add-to-dashboard" from Logs 

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#83]
When “add-to-dashboard” icon is clicked, it opens up a dialog box, when you select “choose existing dashboard”, and if no dashboards are present, we should show a drop-down with no values in it. 
Currently it shows some vertical line but not much after that.

<img width="529" alt="image" src="https://github.com/siglens/siglens/assets/71771131/5ae07664-c074-4eda-9313-d79f8c0cc11f">

**Comment by kaushik-manivannan** [comment]
I will take this up.

**Comment by venkateshamatam** [comment]
I would like to work on this!
