### ISSUE TITLE
 UI : Popup for Alert Name Input on Logs Page

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#84]
On the logs page by add a popup that appears when the user clicks on the bell icon. The popup should include an input box allowing the user to enter the alert name.

<img width="1920" alt="Query Builder Popup - Light Mode 1" src="https://github.com/siglens/siglens/assets/71771131/5808952c-2574-4487-993f-a61e9b65fb9c">

**Comment by kashmii** [comment]
Hi, I would like to work on this issue if it is okay.

**Comment by nkunal** [comment]
Yes please go ahead

**Comment by venkateshamatam** [comment]
I would like to work on this!

**Comment by jqkim6** [comment]
Can I work on this?

**Comment by nbhavana** [comment]
go ahead

**Comment by jqkim6** [comment]
> go ahead

finished and I pull requests
