### ISSUE TITLE
[NEW] Let order of table columns specified by query, eg. with the SPL fields operator

### ISSUE THREAD

**Issue by sekureco42** [siglens/siglens#855]
# Description
Currently the order of the columns in a result set is alphabetically sorted. To present results better - especially on dashboards - it would be nice if the order of the columns could be specified.

# Benefits
Results can be presented in a more natural way to the end user.

# (Optional) Possible Implementation
As mentioned before I would suggest to implement this feature with the (existing) command "`fields`": The result set should respect the order of the specified fields.

# (Optional) Additional Context
Example: Following query is given: `action="block" | stats count(destination_ip) as Count BY source_ip, destination_ip, destination_port | sort -Count`

Now the fields in the table are returned in alphabetical order; meaning the table has columns `destination_ip`, `destination_port`, `source_ip`, `Count` - but my desired order would be `source_ip`, `destination_ip`, `destination_port`, `Count`.

So a command in the future could look like: `action="block" | stats count(destination_ip) as Count BY source_ip, destination_ip, destination_port | sort -Count **| fields source_ip, destination_ip, destination_port, Count**` and it would return the columns in the specified order.

**Comment by sunitakawane** [comment]
Fixed in latest 0.2.6 release PR #897
