### ISSUE TITLE
Address the warning/error that appears when scrolling the Loglines panel.

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#86]
There's a warning and error when scrolling in the Loglines panels.
<img width="1058" alt="image" src="https://github.com/siglens/siglens/assets/71771131/6e944d58-29dc-4c08-8f69-0ab9c00b529b">

**Comment by anshulsharma1610** [comment]
I can work on this

**Comment by AndrewHess** [comment]
Sure, go ahead
