### ISSUE TITLE
[BUG] Splunk aggregation does not work after fields cmd

### ISSUE THREAD

**Issue by Jiale-Fang** [siglens/siglens#885]
# Description
`* | fields state | stats count`
<img width="1378" alt="image" src="https://github.com/siglens/siglens/assets/67371917/06bc1a61-bf15-4211-a28a-6ee9b84302ee">

# Steps to Reproduce
Give detailed step-by-step instructions to help us easily reproduce the issue.
1. ...

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Commit Hash: [e.g. 9ed5f0a]
- OS: [e.g. MacOS 14.1.1 on apple silicon]
- Browser and Version (if applicable): [e.g. chrome 119.0.6045.159 arm64, safari 19616.2.9.11.7]

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by sathkrith** [comment]
I will be working on this

**Comment by AndrewHess** [comment]
Great, go ahead
