### ISSUE TITLE
[NEW]  UI - Dashboard page - add search bar 

### ISSUE THREAD

**Issue by sunitakawane** [siglens/siglens#901]
# Description
On Edit Dashboard page , add search bar at the top
This will be populated with existing column names , filter operator and column values.(similar log search / query builder page)
Once user select a key value pair to set a filter , we should change the queries for  all panels in the current dashboard to add this filter and refresh the dashboard.

![Screenshot 2024-05-17 at 9 11 43 PM](https://github.com/siglens/siglens/assets/10069381/22942764-2b73-47b7-ad25-165a6ae62d5b)

to add filter to all panels of the dashboard
# Benefits
Describe why you want this feature.

# (Optional) Possible Implementation
If you have any ideas on how this should be implemented, let us know here.

# (Optional) Additional Context
Add anything else we should know about this.

**Comment by Axiself** [comment]
I would like to work on this.
