### ISSUE TITLE
Rename functions in segsearch and searchaggs

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#93]
# Description
The segsearch.go and searchaggs.go files define several functions named things like like `applyXYZ` but their naming is a bit inconsistent. Rename them so they are more clear and consistent. You should use the query type and flow when deciding on the name.

# Goals
* For each of the `applyXYZ` functions, propose a new name or to keep it as it is.
* Once these proposed names are approved, change the function names.

**Comment by Eashan7** [comment]
I'm working on this.

**Comment by Eashan7** [comment]
Hello @AndrewHess, @nkunal, here's my proposal for new names for 'applyXYZ' functions in accordance with the query type and flow in segsearch.go and searchaggs.go files. Please let me know if they are fine to go ahead with or any changes are required.

| Sl. No. | Existing Function Name  | Proposed Function Name | Change | Purpose of function
| ------------- | ------------- | ------------- | ------------- | ------------- |
| 1 | applyAggregationsToResult  | applyAggregationsToResult  | No change  | Applies aggregations to the search results based on the provided query aggregators.
| 2 | applyAggregationsSingleBlock  | applyAggregationsToSingleBlock  | Changed  | Applies aggregations for a single block of data.
| 3 | applyAggsToResultFastPath  | applyAggregationsToResultFastPath  | Changed  | Similar to _applyAggregationsToResult_ but optimized for specific scenarios
| 4 | applyAggsSingleBlockFastPath  | applyAggregationsToSingleBlockFastPath  | Changed  | Similar to _applyAggregationsToSingleBlock_ but optimized for specific scenarios
| 5 | applySegStatsToMatchedRecords  | applySegStatsToMatchedRecords  | No change  | Applies segment statistics to matched records.
| 6 | applySegmentStatsUsingDictEncoding  | applySegmentStatsUsingDictEncoding  | No change  | Returns all columns that are not dict encoded
| 7 | ApplyAgileTree  | applyAgileTree | Changed  | Applies Agile Tree to a query

**Comment by Eashan7** [comment]
Sure. Here's the Chatgpt suggestions:
			
Original: applyAggregationsToResult
New Name: ProcessQueryAggregations

Original: applyAggregationsSingleBlock
New Name: AggregateSingleBlockData

Original: applyAggsToResultFastPath
New Name: ProcessQueryAggregationsFastPath

Original: applyAggsSingleBlockFastPath
New Name: AggregateSingleBlockDataFastPath

Original: applySegStatsToMatchedRecords
New Name: ProcessSegmentStatsForMatches

Original: applySegmentStatsUsingDictEncoding
New Name: CalculateEncodedSegmentStatistics

Original: ApplyAgileTree
New Name: ExecuteAgileTreeAggregation

**Comment by nkunal** [comment]
> Sure @nkunal. Here's the Chatgpt suggestions:
> 
> 			
> 
> Original: applyAggregationsToResult
> 
> New Name: ProcessQueryAggregations
> 
> 
> 
> Original: applyAggregationsSingleBlock
> 
> New Name: AggregateSingleBlockData
> 
> 
> 
> Original: applyAggsToResultFastPath
> 
> New Name: ProcessQueryAggregationsFastPath
> 
> 
> 
> Original: applyAggsSingleBlockFastPath
> 
> New Name: AggregateSingleBlockDataFastPath
> 
> 
> 
> Original: applySegStatsToMatchedRecords
> 
> New Name: ProcessSegmentStatsForMatches
> 
> 
> 
> Original: applySegmentStatsUsingDictEncoding
> 
> New Name: CalculateEncodedSegmentStatistics
> 
> 
> 
> Original: ApplyAgileTree
> 
> New Name: ExecuteAgileTreeAggregation

Thanks Eashan, let us review this internally and get back to you. Given the thanksgiving holidays, we will get back to you by next tue/wed

**Comment by AndrewHess** [comment]
The changes you proposed (not the ones from ChatGPT) look good, so you can make those changes. You might need to keep `ApplyAgileTree` capitalized because I think it's used in a different package, but if not you can make it lowercase like you suggested.

Sorry I forgot to follow up on this earlier

**Comment by ChinmayDharwad24** [comment]
I want to work on this

**Comment by AndrewHess** [comment]
Great, go ahead

**Comment by ChinmayDharwad24** [comment]
I have thought about updating the function names with applyXYZ in segsearch.go and searchaggs.go files. Please review and confirm. 

| Filename         | Old Function Name                   | Updated Function Name                | Thought to Update                                              |
|------------------|------------------------------------|--------------------------------------|----------------------------------------------------------------|
| segsearch.go     | applyRawSearchToNode                | executeRawSearchOnNode               | Execution of a raw search on a specific node.                   |
| segsearch.go     | applyRawSearchToConditions          | executeRawSearchWithConditions       | Execution of raw search using certain conditions.               |
| searchaggs.go    | applyAggregationsToResult           | aggregateResults                     | Simplifies the name, clearly stating aggregation of results.    |
| searchaggs.go    | applyAggregationsSingleBlock        | aggregateSingleBlockResults          | Specifies aggregation of results for a single block.           |
| searchaggs.go    | applyAggsToResultFastPath           | aggregateResultsFastPath             | Indicates a faster path for aggregating results.                |
| searchaggs.go    | applyAggsSingleBlockFastPath        | aggregateSingleBlockFastPath         | Denotes a faster aggregation path for a single block.           |
| searchaggs.go    | applySegStatsToMatchedRecords       | applySegmentStatisticsToRecords     | Descriptive, specifying that segment statistics are applied.   |
| searchaggs.go    | applySegmentStatsUsingDictEncoding  | applySegmentStatisticsWithDictEncoding | Simplifies the name          |


* For, ApplyAgileTree -> applyAgileTree
we can refactor it, it is used in seqquery.go file

**Comment by ChinmayDharwad24** [comment]
The PR has some errors. I will update and fix them.
