### ISSUE TITLE
[BUG] Refreshing UI logs page messes up Search Filter with spaces

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#936]
# Description

# Steps to Reproduce
1. Go to logs page on UI
2. Use Query Builder to make a search. Use `address=...` and choose a value that has spaces
<img width="1135" alt="image" src="https://github.com/siglens/siglens/assets/20426590/f81cd1e8-b9ab-4bee-a616-3ab73add6b82">
3. Refresh the page
Now the Query Builder is messed up
<img width="1135" alt="image" src="https://github.com/siglens/siglens/assets/20426590/1fc8ac54-3ca7-473a-828e-f06ff3fcf66f">

# Expected Behavior
Clearly describe what you expect to happen.

# Environment
- Siglens version 0.2.7

# (Optional) Additional Context
Add anything else we should know about this problem.

**Comment by sonamgupta21** [comment]
Resolved in PR #1029
