### ISSUE TITLE
SPL: limit head by condition

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#94]
# Description
SPL uses the `head` command to limit the number of results. See https://docs.splunk.com/Documentation/Splunk/9.1.0/SearchReference/Head

One way to limit results is to specify a boolean expression and then stop sending results once that expression becomes false.

When there's multiple segments being searched, we parallelize searching them. So to properly handle this `head` command, you can do the `head` logic on each segment (but keep one record past what `head` should return) and then merge the results and do the `head` logic on that.

# Testing
### Ingesting Data
To ingest some fake data into siglens for testing. Clone https://github.com/sigscalr/sigscalr-client and then from within that repo run
```
go run main.go ingest esbulk -t 10_000 -d http://localhost:8081/elastic --processCount 1 -n 1 -b 500 -g dynamic-user
```
while siglens is running. You can also run
```
go run main.go ingest esbulk -n 10 -g benchmark -d http://localhost:8081/elastic -t 100_000
```
to ingest the data that is used for the CICD tests. You can clear the `siglens/data/` folder to remove all the data from siglens (you should probably do this only when siglens is not running).

### Querying data
After ingesting some data, you can run some basic manual tests in the siglens UI by searching for something like `city=Boston | head weekday!=Friday` and then comparing against a search that matches everything (a blank search will do this), and then checking that your `head` search stopped when it was supposed to.

## Unit Testing
* Add unit tests to `splParser_test.go` to ensure that this command gets parsed correctly.
* Add CICD tests in `cicd/ingest.csv` and `cicd/restart.csv` 

# Goals
* Implement `head <eval-expression>` for Splunk QL and properly handle the optional `null` and `keeplast` parameters (see the Splunk documentation linked above). You'll implement the parsing in spl.peg and may need to update or add a struct in evaluationstructs.go to handle `head`. Then the logic for performing `head` will probably be in segaggs.go, unless you find a more suitable place.
* Implement tests mentioned above in the Unit Testing section. Feel free to add other unit tests as appropriate

**Comment by KavyaRachana** [comment]
Can i work on this?

**Comment by nbhavana** [comment]
Hi @KavyaRachana Are you still keen on working on this issue, or do you require any assistance in initiating this task?

**Comment by Jiale-Fang** [comment]
It seems like `head block` does not work correctly right now. I ran `city=Boston | head limit = 8`, and it did not work

**Comment by Macbeth98** [comment]
This issue is Completed with PR: #1208
