### ISSUE TITLE
SPL: fillnull

### ISSUE THREAD

**Issue by AndrewHess** [siglens/siglens#95]
# Description
SPL uses the `fillnull` command to replace null values with teh specified default value. See https://docs.splunk.com/Documentation/Splunk/9.1.0/SearchReference/Fillnull

You should make changes to the SPL parser in spl.peg, then install [pigeon](https://pkg.go.dev/github.com/mna/pigeon), and compile `spl.go` by running
```
pigeon -o pkg/ast/spl/spl.go pkg/ast/spl/spl.peg
```

You should update or create a struct in evaluationstructs.go to handle the `fillnull` command. Then your implementation of the `fillnull` logic should probably be inside `segaggs.go`

# Testing
### Ingesting Data
For ingesting data with null values, you can follow the instructions in the description of #38 for ingesting traces from opentelemtry-demo. If you want to remove data ingested into siglens, you can do this by clearing the `siglens/data/` directory--you should probably do this only when siglens is not running.

### Querying data
After ingesting some data, you can run some basic manual tests in the siglens UI by searching for something like `* | fillnull value="hello world"` and checking the results.

## Unit Testing
* Add unit tests to `splParser_test.go` to ensure that this command gets parsed correctly. Make sure you handle all optional parameters.

# Goals
* Implement `fillnull` for Splunk QL and properly handle the optional `value` and `field-list` parameters (see the Splunk documentation linked above).
* Implement tests mentioned above in the Unit Testing section. Feel free to add other unit tests as appropriate

**Comment by sp6370** [comment]
@AndrewHess I would like to pick this up.

**Comment by AndrewHess** [comment]
Fantastic, go for it!

**Comment by sp6370** [comment]
@AndrewHess Is there any closed issue similar to this, which I can use a reference? 
I am still familiarizing myself with the codebase.

Also, Is there any doc to understand how SPL parser is used in larger context of the product?

**Comment by AndrewHess** [comment]
Yeah there's been a couple other SPL PRs, for example https://github.com/siglens/siglens/pull/17

**Comment by sp6370** [comment]
`requests are handled by ParseRequest()` What requests are you referring to here?

**Comment by AndrewHess** [comment]
I meant a search request, but that was a little confusing. When you do a search, either the `/api/search` or `/api/search/ws` endpoint will be called. Then `/api/search` for example will call `ProcessPipeSearchRequest()` which uses `ParseRequest()` to parse the search request and generate the AST for that search. Then `ProcessPipeSearchRequest()` calls `ExecuteQuery()` to actually run the search.

**Comment by sp6370** [comment]
Got it!

So here's my understanding in context of this issue:
- We want to support the Splunk query language.
- Any request for search made in form of Splunk query language, we need to handle the `Fillnull` command.

**Comment by sp6370** [comment]
Thanks a lot for the explanation and your patience. 😃

**Comment by sp6370** [comment]
@AndrewHess I'm going to unassign myself from the issue. Unfortunately, I don't have the bandwidth at the moment, and I don't want to hinder others from contributing. Thanks for understanding.

**Comment by basupatil1213** [comment]
I want to work on this

**Comment by nbhavana** [comment]
go ahead
