### ISSUE TITLE
UI : Remove "Eye Icon" from Actions Column in Alert Rules Table

### ISSUE THREAD

**Issue by sonamgupta21** [siglens/siglens#99]
# Description:
The current implementation displays a detailed overview of a specific alert when the user clicks on the "eye icon" in the actions column. However, we have the same functionality when the user clicks on the specific alert row. Therefore, we want to remove the "eye icon" from the actions column.

# Steps to Reproduce:

1. Navigate to the Alerting screen.
2. Add a new alert rule.
3. Observe the alert rules table; the created alert is displayed with an "eye icon" in the actions column.
4. Click on the "eye icon" to view the detailed overview.

# Screenshot: 
<img width="1345" alt="image" src="https://github.com/siglens/siglens/assets/71771131/eaf2275f-3296-46a3-8396-89e7f315a44d">

# Note: 
Remove the "eye icon" functionality from the actions column for newly created alerts. Ensure that the detailed overview functionality is still accessible by clicking on the specific alert row.

**Comment by Sriya03** [comment]
Can I work on this issue?
